### ISSUE TITLE
expected_update_rate is in units of nanoseconds, not seconds 

### ISSUE THREAD

**Issue by Jconn** [ros-planning/navigation2#1054]
I am experimenting with the expected_update_rate param  of the observation_sources 

I couldn't find units for them and assumed they were in seconds. 

My params were like this:

```
observation_sources: pointcloud
      pointcloud:
        topic: /object_pc
        max_obstacle_height: 4.0
        clearing: True
        marking: True
        expected_update_rate: 1.0
```

After I changed my expected_update_rate to 10^8, i.e.

```
observation_sources: pointcloud
      pointcloud:
        topic: /object_pc
        max_obstacle_height: 4.0
        clearing: True
        marking: True
        expected_update_rate: 100000000.0

```

 I started getting a warning that I wasn't reaching my update rate of .1 seconds. 

Should I be specifying this param in nanoseconds? It's confusing that it requires a double if that is the case.
