### ISSUE TITLE
Does nav2 costmap_2d currently support multiple obstacle layers?

### ISSUE THREAD

**Issue by zachfang** [ros-planning/navigation2#1355]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Version or commit hash:
  - ros-dashing-nav2-costmap-2d	0.2.6-1bionic.20191017.211223
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
YAML file used: 
```
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      plugin_names: ["static_layer", "obstacle_layer_1", "obstacle_layer_2", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::StaticLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      always_send_full_costmap: True
      rolling_window: False
      update_frequency: 30.0
      publish_frequency: 1.0
      resolution: 0.05
      global_frame: map
      robot_base_frame: base_link
      footprint: "[[0.5, 0.5], [0.5, -0.5], [-0.5, -0.5], [-0.5, 0.5]]"
      lethal_cost_threshold: 200
      obstacle_layer_1:
        enabled: True
        observation_sources: points_1
        max_obstacle_height: 2.5
        points_1:
          data_type: PointCloud2
          topic: /points_1
          max_obstacle_height: 2.5
          min_obstacle_height: 0.05
          raytrace_range: 10.0
          obstacle_range: 10.0
          clearing: True
          marking: True
      obstacle_layer_2:
        enabled: True
        observation_sources: points_2
        max_obstacle_height: 2.5
        points_2:
          data_type: LaserScan
          topic: /points_2
          max_obstacle_height: 2.5
          min_obstacle_height: 0.0
          raytrace_range: 10.0
          obstacle_range: 10.0
          clearing: True
          marking: True
      inflation_layer:
        inflation_radius: 0.2
        cost_scaling_factor: 10.0
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      plugin_names: ["static_layer", "obstacle_layer_1", "obstacle_layer_2", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::StaticLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      always_send_full_costmap: True
      rolling_window: True
      update_frequency: 30.0
      publish_frequency: 3.0
      resolution: 0.05
      global_frame: odom
      robot_base_frame: base_link
      footprint: "[[0.5, 0.5], [0.5, -0.5], [-0.5, -0.5], [-0.5, 0.5]]"
      lethal_cost_threshold: 99
      width: 10
      height: 10
      obstacle_layer_1:
        enabled: True
        observation_sources: points_1
        max_obstacle_height: 2.5
        points_1:
          data_type: PointCloud2
          topic: /points_1
          max_obstacle_height: 2.5
          min_obstacle_height: 0.05
          raytrace_range: 10.0
          obstacle_range: 10.0
          clearing: True
          marking: True
      obstacle_layer_2:
        enabled: True
        observation_sources: points_2
        max_obstacle_height: 2.5
        points_2:
          data_type: LaserScan
          topic: /points_2
          max_obstacle_height: 2.5
          min_obstacle_height: 0.0
          raytrace_range: 10.0
          obstacle_range: 10.0
          clearing: True
          marking: True
      inflation_layer:
        inflation_radius: 0.2
        cost_scaling_factor: 5.0
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False
```

#### Expected behavior
The costmap should have two obstacle layers with separate observation sources and inflation layer inflates difference sensor reading in the final local/global costmap. 

#### Actual behavior
Only static and inflation layers are initialized properly, and obstacle layers are missing topic and other parameters.
![Screenshot from 2019-11-13 12-56-42](https://user-images.githubusercontent.com/9645925/68790400-3fa3ca00-0615-11ea-9c2e-d9460d39ddab.png)
(For illustration use only, the robot was not localized correctly.)

```
[dwb_controller-15] [INFO] [local_costmap.local_costmap]: Using plugin "static_layer"
[dwb_controller-15] [INFO] [local_costmap.local_costmap]: Subscribing to the map topic (/map) with transient local durability
[dwb_controller-15] [INFO] [local_costmap.local_costmap]: Using plugin "obstacle_layer_1"
[dwb_controller-15] [INFO] [local_costmap.local_costmap]: Subscribed to Topics: 
[dwb_controller-15] [INFO] [local_costmap.local_costmap]: Using plugin "obstacle_layer_2"
[dwb_controller-15] [INFO] [local_costmap.local_costmap]: Subscribed to Topics: 
[dwb_controller-15] [INFO] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[dwb_controller-15] [INFO] [local_costmap.local_costmap]: StaticLayer: Resizing static layer to 340 X 572 at 0.050000 m/pix
```

```
ros2 param get /local_costmap/local_costmap plugin_names
String values are: ['static_layer', 'obstacle_layer_1', 'obstacle_layer_2', 'inflation_layer']
ros2 param get /local_costmap/local_costmap obstacle_layer_1.enabled
Boolean value is: True
ros2 param get /local_costmap/local_costmap obstacle_layer_1.max_obstacle_height
Double value is: 2.5
ros2 param get /local_costmap/local_costmap obstacle_layer_1.observation_sources
Parameter not set.
```
#### Additional information
Follow ROS2 layer configuration example https://github.com/ros-planning/navigation2/tree/master/nav2_costmap_2d.

By looking into the code, https://github.com/ros-planning/navigation2/blob/master/nav2_costmap_2d/src/costmap_2d_ros.cpp#L93 should not be in the top level as it's for each obstacle layer specifically, also it's not used anywhere in this file.

From here https://github.com/ros-planning/navigation2/blob/dashing-devel/nav2_costmap_2d/plugins/obstacle_layer.cpp#L91, looks like namespacing is not propagate properly and thus obstacle layer is looking for top level observation_sources rather than observation_sources specified for each of them.
