### ISSUE TITLE
Navigation2: Example not working(turtlebot3) rviz not responding

### ISSUE THREAD

**Issue by ShivamPR21** [ros-planning/navigation2#1800]
## Bug report
While running example provided in the getting-started section of Navigation2 docs: https://navigation.ros.org/getting_started/index.html#running-the-example the rviz2 navigation panel get irresponsive and following warnings appear in terminal continuously for a long time(until interrupted):

```
[rviz2-4] [INFO] [1591805889.182378907] [rviz2]: Message Filter dropping message: frame 'base_scan' at time 104.002 for reason 'Unknown'
[rviz2-4] [INFO] [1591805889.249745739] [rviz2]: Message Filter dropping message: frame 'odom' at time 0.000 for reason 'Unknown'
[rviz2-4] [INFO] [1591805889.250428044] [rviz2]: Message Filter dropping message: frame 'odom' at time 104.024 for reason 'Unknown'
[planner_server-9] [INFO] [1591805889.391656631] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist

``` 

**Required Info:**

- Operating System:
  - 
   Ubuntu 20.04
- Version or commit hash:
  - 
  Master
- DDS implementation:
  - 
  Fast-RTPS

-Installation type
  Source

#### Steps to reproduce issue

```
source /home/shivam/ros2_foxy/install/setup.zsh

# add ros2_perception image_common 
source /home/shivam/ros2_perception/install/setup.zsh

# add gazebo 
source /usr/share/gazebo/setup.sh

# add gazebo ros packages
source /home/shivam/gazebo_sim/ros2_pkgs/install/setup.zsh

# add navigation2 packages to system
source /home/shivam/ros2_foxy_experimentals/install/setup.zsh

# turtle_bot3
export TURTLEBOT3_MODEL=waffle

export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/shivam/ros2_foxy_experimentals/install/turtlebot3_gazebo/share/turtlebot3_gazebo/models

ros2 launch nav2_bringup tb3_simulation_launch.py
```

#### Additional information

Here is my ```vcs export src --exact-with-tags``` output:-

ros2 install:-
```
same as foxy release ros2.repos
```
navigation2 and turtlebot3 install:-
```
repositories:
  BehaviorTree.CPP:
    type: git
    url: https://github.com/BehaviorTree/BehaviorTree.CPP.git
    version: 83cbcebb2f3321472f49145735365b4076770a5f
  angles:
    type: git
    url: https://github.com/ros/angles.git
    version: a1b83de2f242db3602788eae7a8aaa30300bc502
  navigation2:
    type: git
    url: https://github.com/ros-planning/navigation2.git
    version: 9e304b1ad4c10d03f7a08991224fd9686c6bb26d
  slam_toolbox:
    type: git
    url: https://github.com/SteveMacenski/slam_toolbox.git
    version: 2.2.0
  turtlebot3/turtlebot3:
    type: git
    url: https://github.com/ROBOTIS-GIT/turtlebot3.git
    version: 1ff16b4831aa8b4478b2c2e5a59376673635683c
  turtlebot3/turtlebot3_msgs:
    type: git
    url: https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git
    version: 348b3260fa857a1d9af96ccffc2faa387e0e6a48
  turtlebot3/turtlebot3_simulations:
    type: git
    url: https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git
    version: 9ecdd65e6bb4784bb51a7f4c0178296abb447b7a
  utils/DynamixelSDK:
    type: git
    url: https://github.com/ROBOTIS-GIT/DynamixelSDK.git
    version: 3340663b5bdf9c2ff27cc23ad7d0d3dd02412380
  utils/hls_lfcd_lds_driver:
    type: git
    url: https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver.git
    version: 626081d9ce3aaa66f5adb90d09b74cb352c311da
```
