### ISSUE TITLE
Hybrid-A* / Smac planner: backtrace function runs into infinite loops

### ISSUE THREAD

**Issue by dkuenster** [ros-planning/navigation2#2040]
## Bug report

**Required Info:**

- Operating System:
  - Debian 10
- ROS2 Version:
  - rolling
- Version or commit hash:
  - a13623922bc93ec8f12cdd40d2a817ea54998aaf (current nav2 main)
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue

Start tb3 simulation with ros2 launch nav2_bringup tb3_simulation_launch.py. Replace planner_server parameters in nav2_params with the ones suggested in 
https://github.com/ros-planning/navigation2/blob/d3fc28af28df764a153c85434f8b30270e963622/smac_planner/README.md#parameters
Set multiple waypoints and look at the memory usage of your system. If your used memory suddenly goes to 100% in a matter of about 15 seconds when reaching a waypoint look for the error message described below.

#### Expected behavior

Planner reaches one waypoint after the other and then plans to the next one.

#### Actual behavior

Sometimes when switching from one waypoint to the next, the planner gets stuck in an infinite loop during the backtrace function.
https://github.com/ros-planning/navigation2/blob/a13623922bc93ec8f12cdd40d2a817ea54998aaf/smac_planner/src/a_star.cpp#L290-L291. 
https://github.com/ros-planning/navigation2/blob/a13623922bc93ec8f12cdd40d2a817ea54998aaf/smac_planner/src/a_star.cpp#L448-L463
It keeps backtracing until it runs out of memory and then crashes with a std::bad_alloc.

#### Error output

[controller_server-8] [INFO] [1602599767.854334277] [controller_server]: Passing new path to controller.
[controller_server-8] [INFO] [1602599769.362043128] [controller_server]: Reached the goal!
[bt_navigator-11] [INFO] [1602599769.387884280] [bt_navigator]: Navigation succeeded
[waypoint_follower-12] [INFO] [1602599770.074093025] [waypoint_follower]: Succeeded processing waypoint 0, processing waypoint task execution
[waypoint_follower-12] [INFO] [1602599770.074309872] [waypoint_follower]: Task execution at waypoint 0 succeeded
[waypoint_follower-12] [INFO] [1602599770.074368300] [waypoint_follower]: Handled task execution on waypoint 0, moving to next.
[bt_navigator-11] [INFO] [1602599770.125854408] [bt_navigator]: Begin navigating from current location to (-1.74, -0.06)
[planner_server-9] [WARN] [1602599786.702648352] [planner_server]: GridBased plugin failed to plan calculation to (1.91, -0.09): "std::bad_alloc"
[planner_server-9] [WARN] [1602599786.705805908] [planner_server_rclcpp_node]: [compute_path_to_pose] [ActionServer] Client requested to cancel the goal. Cancelling.
[planner_server-9] It took 3.68827 milliseconds with 396 iterations.
[controller_server-8] [INFO] [1602599786.750957954] [controller_server]: Received a goal, begin computing control effort.

#### asan Backtrace

![asan](https://user-images.githubusercontent.com/14927048/95868663-c18efc80-0d6a-11eb-9e1c-22cd72e4df7b.png)

#### Debug Output
I printed the current node index and path size in each while loop of the backtrace. It seems to get stuck in a loop of only 3 nodes.

```   
   while (current_node->parent) {
     path.push_back(current_node->pose);
     current_node = current_node->parent;
     std::cout << "Current Node = "  << current_node->getIndex() << " Path size =  " << path.size() << std::endl;
   }
```

It took 118.231 milliseconds with 1 iterations.
Current Node = 20651835 Path size =  1
Current Node = 20597980 Path size =  2
Current Node = 20597907 Path size =  3
Current Node = 20544050 Path size =  4
Current Node = 20597834 Path size =  5
It took 113.746 milliseconds with 1 iterations.
Current Node = 20651835 Path size =  1
Current Node = 20651764 Path size =  2
Current Node = 20597907 Path size =  3
Current Node = 20597835 Path size =  4
It took 137.276 milliseconds with 1 iterations.
Current Node = 20651834 Path size =  1
Current Node = 20651761 Path size =  2
Current Node = 20651690 Path size =  3
Current Node = 20651619 Path size =  4
It took 127.842 milliseconds with 1 iterations.
Current Node = 20651834 Path size =  1
Current Node = 20651691 Path size =  2
It took 134.659 milliseconds with 1 iterations.
(Here it reaches one waypoint and starts planning to the next one)
Current Node = 20651835 Path size =  1
Current Node = 20651763 Path size =  2
Current Node = 20597906 Path size =  3
Current Node = 20597834 Path size =  4
Current Node = 20651763 Path size =  5
Current Node = 20597906 Path size =  6
Current Node = 20597834 Path size =  7
Current Node = 20651763 Path size =  8
Current Node = 20597906 Path size =  9
Current Node = 20597834 Path size =  10
Current Node = 20651763 Path size =  11
Current Node = 20597906 Path size =  12
Current Node = 20597834 Path size =  13
Current Node = 20651763 Path size =  14
Current Node = 20597906 Path size =  15
Current Node = 20597834 Path size =  16
Current Node = 20651763 Path size =  17
Current Node = 20597906 Path size =  18
Current Node = 20597834 Path size =  19
Current Node = 20651763 Path size =  20
Current Node = 20597906 Path size =  21
Current Node = 20597834 Path size =  22
Current Node = 20651763 Path size =  23
Current Node = 20597906 Path size =  24
...

**Comment by SteveMacenski** [comment]
I haven't experienced this, what happens if you navigate to a pose, get there, go to a next pose, ... without use of the nav2_waypoint_follower? Or using the waypoint_follower but setting the sleep time to 100ms or similar.

What I suspect is happening is a bug in the rclcpp action server implementation where 2 requests are juuust barely overlapping, but want to verify.

**Comment by masdoost** [comment]
> Current Node = 20597834 Path size = 4
> Current Node = 20651763 Path size = 5
> Current Node = 20597906 Path size = 6
> Current Node = 20597834 Path size = 7

There seems to be circular relation in the nodes of the astar tree. Looks more like a bug in astar implementation, e.g. already visited nodes are not marked as visited correctly..

Could an asynchronity of two request cause the astar tree to be malformed?

**Comment by SteveMacenski** [comment]
I did notice that, that's why I asked about the waypoint follower use.

**Comment by dkuenster** [comment]
It happens also if I don't use the waypoint follower and manually navigate from pose to pose with some waiting time.
It doesn't happen every time and it doesn't seem to happen very often in the standard tb3 scenario. I have a custom scenario with a larger and more open map, where it happens more frequently. I am not sure what exactly triggers it however.

**Comment by SteveMacenski** [comment]
> But always at the end of the path. I'm starting to think in the waypoint case it also happened at the very end of the current path, instead of when initially planning to the new waypoint.

This is a really helpful insight, I think that might be evidence that we have a bug in the analytic expansion part of the code (which is a really good sign, that should be an easy fix then!). To validate that, comment out this function https://github.com/ros-planning/navigation2/blob/main/smac_planner/src/a_star.cpp#L337-L419 (the NodeT templated version below it will take over). The planner will get slower, but let us know if you then see this issue. If that isn't the issue, then I'll need to jump in and take a deep look (reproduction instructions would be helpful since I still haven't seen it).  If that is the issue, we should be able to narrow it down quickly.

**Comment by dkuenster** [comment]
The loops do in fact disappear when I comment out that function (https://github.com/ros-planning/navigation2/blob/main/smac_planner/src/a_star.cpp#L337-L419).

I added the following outputs:
```
 // Legitimate path - set the parent relationships - poses already set
  prev = node;
  for (const auto & node_pose : possible_nodes) {
    const auto & n = node_pose.first;
    n->parent = prev;
    prev = n;
  }
  std::cout << "size possible_nodes: " << possible_nodes.size() << std::endl;
  _goal->parent = prev;
  return _goal;
```
```
    // 2.a) Use an analytic expansion (if available) to generate a path
    // to the goal.
    NodePtr result = tryAnalyticExpansion(
      current_node, neighborGetter, analytic_iterations,
      closest_distance);
    if (result != nullptr) {
      current_node = result;
      std::cout << "Did Expansion arrive at goal? " << isGoal(current_node) << std::endl;
    }
```

The expansion seems to always arrive at the goal, I couldn't find a case where the output was false. 

```
[planner_server-9] [INFO] [1602765128.674847303] [planner_server]: Attempting to a find path from (-210.83, -63.10) to (-212.53, -64.42).
[planner_server-9] size possible_nodes: 7
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] It took 75.5394 milliseconds with 1 iterations.
[planner_server-9] [INFO] [1602765128.750468557] [planner_server]: Found valid path of size 8 to (-212.53, -64.42)
[controller_server-8] [INFO] [1602765128.942069206] [controller_server]: Passing new path to controller.
[planner_server-9] [INFO] [1602765128.972421098] [planner_server]: Attempting to a find path from (-210.69, -63.03) to (-212.53, -64.42).
[planner_server-9] size possible_nodes: 5
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] It took 70.5963 milliseconds with 1 iterations.
[planner_server-9] [INFO] [1602765129.043184669] [planner_server]: Found valid path of size 6 to (-212.53, -64.42)
[controller_server-8] [INFO] [1602765129.142123904] [controller_server]: Passing new path to controller.
[planner_server-9] [INFO] [1602765129.261814617] [planner_server]: Attempting to a find path from (-210.73, -63.05) to (-212.53, -64.42).
[planner_server-9] size possible_nodes: 6
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] Breaking because we detected a loop
[planner_server-9] It took 54.3005 milliseconds with 4 iterations.
[planner_server-9] [INFO] [1602765129.316206527] [planner_server]: Found valid path of size 8 to (-212.53, -64.42)
[planner_server-9] [INFO] [1602765129.540570725] [planner_server]: Attempting to a find path from (-210.76, -63.07) to (-212.53, -64.42).
[controller_server-8] [INFO] [1602765129.542021785] [controller_server]: Passing new path to controller.
[planner_server-9] size possible_nodes: 6
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] Breaking because we detected a loop
[planner_server-9] It took 58.8829 milliseconds with 4 iterations.
[planner_server-9] [INFO] [1602765129.599985702] [planner_server]: Found valid path of size 8 to (-212.53, -64.42)
[controller_server-8] [INFO] [1602765129.742024285] [controller_server]: Passing new path to controller.
[planner_server-9] [INFO] [1602765129.826746431] [planner_server]: Attempting to a find path from (-210.89, -63.16) to (-212.53, -64.42).
[planner_server-9] size possible_nodes: 2
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] It took 55.5939 milliseconds with 1 iterations.
[planner_server-9] [INFO] [1602765129.883290875] [planner_server]: Found valid path of size 3 to (-212.53, -64.42)
[planner_server-9] [INFO] [1602765133.094818419] [planner_server]: Attempting to a find path from (-210.78, -63.08) to (-212.53, -64.42).
[controller_server-8] [INFO] [1602765133.142066253] [controller_server]: Passing new path to controller.
[planner_server-9] size possible_nodes: 6
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] Breaking because we detected a loop
[planner_server-9] It took 58.496 milliseconds with 4 iterations.
[planner_server-9] [INFO] [1602765133.153573975] [planner_server]: Found valid path of size 8 to (-212.53, -64.42)
[controller_server-8] [INFO] [1602765133.342062123] [controller_server]: Passing new path to controller.
[planner_server-9] [INFO] [1602765133.381233223] [planner_server]: Attempting to a find path from (-210.65, -62.99) to (-212.53, -64.42).
[planner_server-9] size possible_nodes: 6
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] Breaking because we detected a loop
[planner_server-9] It took 52.8564 milliseconds with 4 iterations.
[planner_server-9] [INFO] [1602765133.434237836] [planner_server]: Found valid path of size 8 to (-212.53, -64.42)
[controller_server-8] [INFO] [1602765133.542021152] [controller_server]: Passing new path to controller.
[planner_server-9] [INFO] [1602765133.660021930] [planner_server]: Attempting to a find path from (-210.52, -62.91) to (-212.53, -64.42).
[planner_server-9] size possible_nodes: 6
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] Breaking because we detected a loop
[planner_server-9] It took 63.7058 milliseconds with 4 iterations.
[planner_server-9] [INFO] [1602765133.724779513] [planner_server]: Found valid path of size 8 to (-212.53, -64.42)
[planner_server-9] [INFO] [1602765133.939171548] [planner_server]: Attempting to a find path from (-210.51, -62.90) to (-212.53, -64.42).
[controller_server-8] [INFO] [1602765133.942027802] [controller_server]: Passing new path to controller.
[planner_server-9] size possible_nodes: 6
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] Breaking because we detected a loop
[planner_server-9] It took 49.5109 milliseconds with 4 iterations.
[planner_server-9] [INFO] [1602765133.989352561] [planner_server]: Found valid path of size 8 to (-212.53, -64.42)
[controller_server-8] [INFO] [1602765134.142111680] [controller_server]: Passing new path to controller.
[planner_server-9] [INFO] [1602765134.222062173] [planner_server]: Attempting to a find path from (-210.68, -63.02) to (-212.53, -64.42).
[planner_server-9] size possible_nodes: 6
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] Breaking because we detected a loop
[planner_server-9] It took 64.3725 milliseconds with 4 iterations.
[planner_server-9] [INFO] [1602765134.286523948] [planner_server]: Found valid path of size 8 to (-212.53, -64.42)
[controller_server-8] [INFO] [1602765134.342025244] [controller_server]: Passing new path to controller.
[planner_server-9] [INFO] [1602765134.515552421] [planner_server]: Attempting to a find path from (-210.99, -63.23) to (-212.53, -64.42).
[planner_server-9] size possible_nodes: 2
[planner_server-9] Did Expansion arrive at goal? 1
[planner_server-9] It took 48.442 milliseconds with 1 iterations.
[planner_server-9] [INFO] [1602765134.564090427] [planner_server]: Found valid path of size 3 to (-212.53, -64.42)
```

**Comment by SteveMacenski** [comment]
OK - so something to do with the analytic expansion but not the last node being incorrect or looping on that front.

Another thing @james-ward and I spoke about was checking if the nodes were visited in the case that you detect a loop. What he thought is that if the plan had expanded nodes in A* search that intersected with the analytic expansion, when we set the parent nodes, it could be messing something up. 

So I think to test that in the analytic expansion we should check if the node was visited [around here](https://github.com/ros-planning/navigation2/blob/main/smac_planner/src/a_star.cpp#L386). We still need to use that node, but if we see that every time we have a detected loop it also happened with a node in the expansion being already visited (and when no loop, no visited in path). 

Some minimal setup to reproduce would be nice still so we can test alongside you.

**Comment by dkuenster** [comment]
```
    GridBased:
      plugin: "smac_planner/SmacPlanner"
      tolerance: 5.0                    # tolerance for planning if unable to reach exact pose, in meters
      downsample_costmap: True         # whether or not to downsample the map
      downsampling_factor: 4            # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      allow_unknown: false              # allow traveling in unknown space
      max_iterations: -1                # maximum total iterations to search for before failing
      max_on_approach_iterations: 1000  # maximum number of iterations to attempt to reach goal once in tolerance
      max_planning_time_ms: 2000.0      # max time in ms for planner to plan and smooth. Will scale maximum smoothing times based on remaining time after planning.
      smooth_path: false                 # Whether to smooth searched path
      motion_model_for_search: "REEDS_SHEPP"  # 2D Moore, Von Neumann; SE2 Dubin, Redds-Shepp
      angle_quantization_bins: 72       # For SE2 node: Number of angle bins for search, must be 1 for 2D node (no angle search)
      minimum_turning_radius: 10.0      # For SE2 node & smoother: minimum turning radius in m of path / vehicle
      reverse_penalty: 4.2              # For Reeds-Shepp model: penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.50              # For SE2 node: penalty to apply if motion is changing directions, must be >= 0
      non_straight_penalty: 1.10        # For SE2 node: penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 1.3                 # For SE2 node: penalty to apply to higher cost zones, must be >= 0

      smoother:
        smoother:
          w_curve: 30.0                 # weight to minimize curvature of path
          w_dist: 0.0                   # weight to bind path to original as optional replacement for cost weight
          w_smooth: 30000.0             # weight to maximize smoothness of path
          w_cost: 0.025                 # weight to steer robot away from collision and cost
          cost_scaling_factor: 10.0     # this should match the inflation layer's parameter

        optimizer:
          max_time: 0.10                # maximum compute time for smoother
          max_iterations: 500           # max iterations of smoother
          debug_optimizer: false        # print debug info
          gradient_tol: 1.0e-10         # gradient change termination tolerance
          fn_tol: 1.0e-20               # function change termination tolerance
          param_tol: 1.0e-15            # parameter block change termination tolerance
          advanced:                     # I do not recommend users mess with this unless they're doing production tuning
            min_line_search_step_size: 1.0e-20
            max_num_line_search_step_size_iterations: 50
            line_search_sufficient_function_decrease: 1.0e-20
            max_num_line_search_direction_restarts: 10
            max_line_search_step_expansion: 50
```

Try using these parameters on an empty map. It seems to be somehow tied to the large minimum turning. I could reproduce it far more frequently this way.
