### ISSUE TITLE
publish_voxel_map: false in voxel_layer crashes navigation stack

### ISSUE THREAD

**Issue by xivien** [ros-planning/navigation2#2120]
## Bug report

**Required Info:**

- Operating System:
  -Ubuntu 20.04
- ROS2 Version:
  - Ros2 Foxy
- Version or commit hash:
  - ros-foxy-navigation2	0.4.3-1focal.20201103.171126
- DDS implementation:
  - default

#### Steps to reproduce issue
When using voxel layer in a costmap, setting publish_voxel_map to false causes the navigation stack to crash. Rest of parameters are default from wiki
```
voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        footprint_clearing_enabled: true
        max_obstacle_height: 2.0
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        unknown_threshold: 15
        mark_threshold: 0
        observation_sources: pointcloud
        combination_method: 1
        pointcloud:  # no frame set, uses frame from message
          topic: /intel_realsense_r200_depth/points
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          obstacle_range: 2.5
          raytrace_range: 3.0
          clearing: True
          marking: True
          data_type: "PointCloud2"
```
```
[ERROR] [controller_server-1]: process has died [pid 25843, exit code -11, cmd '/opt/ros/foxy/lib/nav2_controller/controller_server --ros-args -r /tf:=tf -r /tf_static:=tf_static --params-file /tmp/tmp0343mgs1'].

```

#### Expected behavior
Costmap launches without publishing /local_costmap/voxel_grid topic

#### Actual behavior
Navigation stack crashes
#### Additional information
It may be related to this line https://github.com/ros-planning/navigation2/blob/8bd158af79b942f4053206674a33b403e6c144e4/nav2_costmap_2d/plugins/voxel_layer.cpp#L98
