### ISSUE TITLE
Controller server aborts the action server handle

### ISSUE THREAD

**Issue by abylikhsanov** [ros-planning/navigation2#2190]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Foxy binaries
- Version or commit hash:
  - From source latest navigation2 release (0.4.5)
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
Launch gazebo simulation (turtlebot3 spawn) on a stationary PC and launch a sample navigation2 launch file on a less powerful ARM machine (for example RPi4). The idea is to run all heavy algorithms on ARM machine while sensor simulation comes from Gazebo (just a simple hardware in a loop).

As this issue comes from the controller node, use this `FollowPath` parameters (you can omit holonomic critic) :
```
FollowPath:
      GoalAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalDist.scale: 24.0
      ObstacleFootprintCritic.scale: 1.0
      PathAlign.forward_point_distance: 1.0
      PathAlign.scale: 32.0
      PathDist.scale: 32.0
      RotateToGoal.lookahead_time: 2.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      Twirling.scale: 10.0
      Holonomic.scale: 40.0
      acc_lim_theta: 1.0
      acc_lim_x: 0.5
      acc_lim_y: 0.3
      angular_granularity: 0.025
      critics:
        - RotateToGoal
        - Oscillation
        - ObstacleFootprintCritic
        - GoalAlign
        - PathAlign
        - PathDist
        - GoalDist
        - Twirling
        - Holonomic
      debug_trajectory_details: false
      decel_lim_theta: -1.0
      decel_lim_x: -0.5
      decel_lim_y: -0.5
      linear_granularity: 0.05
      max_speed_xy: 0.7
      max_vel_theta: 1.0
      max_vel_x: 0.7
      max_vel_y: 0.2
      min_speed_theta: 0.0
      min_speed_xy: -0.7
      min_vel_x: -0.7
      min_vel_y: -0.2
      plugin: dwb_core::DWBLocalPlanner
      short_circuit_trajectory_evaluation: true
      sim_time: 2.0
      stateful: true
      trans_stopped_velocity: 0.25
      transform_tolerance: 0.2
      vtheta_samples: 40
      vx_samples: 20
      vy_samples: 20
      xy_goal_tolerance: 0.1
```

#### Expected behavior

I have tested this on my stationary PC first and it should run normally where robot can navigate and avoid obstacles. So nothing extraordinary

#### Actual behavior

Controller server constantly aborts the handle and the loop itself seems to be slow (on my local pc, I get regularly a message that the control loop missed its desired rate of 5Hz but the frequency of those messages are much higher than on a lower end ARM machine.

I first thought that DWB configuration I have is so heavy that my ARM machine simply cannot handle but interesingly, the CPU load is below average. The controller server only consumes 1 full core (103% usage out of 400). 

Therefore, I am a bit confused. Does the controller have a limit of amount of cores it can use?
