### ISSUE TITLE
Robots doesn't move when a new costmap plugin is adding

### ISSUE THREAD

**Issue by EtienneSchmitz** [ros-planning/navigation2#2316]
## Bug report

**Required Info:**

- Operating System: Ubuntu 20.04
- ROS2 Version: Rolling (ROS 2 Main)
- Version or commit hash: 4066ab943f397e2db68cc6851680d4748c771ffe.
- DDS implementation: rmw_cyclonedds_cpp (default)

#### Steps to reproduce issue

1. Clone this repository [navigation2_tutorials](https://github.com/ros-planning/navigation2_tutorials)

2. Add in global_costmap (nav2_params.yaml) :

```yaml
global_costmap:
  global_costmap:
    ros__parameters:
    ...
        plugins: ["static_layer", "obstacle_layer", "inflation_layer", "gradient_layer"]
        ...
        gradient_layer:
            plugin: nav2_gradient_costmap_plugin/GradientLayer
            enabled: False
```

3. Launch the turtlebot3 :

```bash
    ros2 launch nav2_bringup tb3_simulation_launch.py
```

#### Expected behavior

The stack works and the robots moves.

#### Actual behavior

Robots doesn't move. On Groot, it seems to be blocked on the ComputePathToPose on the BT.
![Capture d’écran du 2021-04-18 09-41-43](https://user-images.githubusercontent.com/20494573/115138640-a957ad00-a02d-11eb-91ad-8a4ae92313e2.png)

#### Additional information

When I switch to ROS Rolling and navigation master for my robots (SSL Robots), I try my costmap plugins and the robots doesn't move on the simulator when I activate it.
I try to figure out if it is a bug on my side or a bug on the navigation stack by testing on the turtlebot3 simulation with the costmap created on the navigation tutorials. 
It's seems to have the same behavior that I have on my own stack.
