### ISSUE TITLE
[Bug] The goal sent to the planner is off the global costmap (even though it's not)

### ISSUE THREAD

**Issue by XDGFX** [ros-planning/navigation2#2545]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04.2 LTS (`ros:foxy` docker container)
- ROS2 Version:
  - Foxy from `ros:foxy` container (I assume binaries?)
- Version or commit hash:
  - 0.4.7-1focal.20210701.142448
- DDS implementation:
  - I think Fast-DDS. Running host networking on all containers, and sharing PID and /dev/shm to allow communication

#### Steps to reproduce issue
Enable rolling global costmap
```yaml
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.15
      resolution: 0.05
      track_unknown_space: true
      rolling_window: true
      width: 6
      height: 6
      origin_x: -3.0
      origin_y: -3.0
```

Move robot outside original global costmap window
![image](https://user-images.githubusercontent.com/16356208/132193031-ae62ec70-87ba-4c33-9673-38e48502d24a.png)

Attempt to navigate to a reasonable point
![image](https://user-images.githubusercontent.com/16356208/132193580-32496cc1-c2d4-4132-949d-f91bd79cd12e.png)

#### Expected behavior
The Nav2 stack receives the request and calculates a valid path

#### Actual behavior
The Nav2 stack receives the request but throws an error:
```log
[planner_server-2] [WARN] [1630919499.639906111] [planner_server]: The goal sent to the planner is off the global costmap. Planning will always fail to this goal.
[planner_server-2] [WARN] [1630919499.640326373] [planner_server]: GridBased: failed to create plan with tolerance 0.50.
[planner_server-2] [WARN] [1630919499.640414502] [planner_server]: Planning algorithm  failed to generate a valid path to (-7.29, 15.41)
[planner_server-2] [WARN] [1630919499.640629577] [planner_server_rclcpp_node]: [compute_path_to_pose] [ActionServer] Aborting handle.
```
