### ISSUE TITLE
SMAC Planner 2d may plan over borders of map

### ISSUE THREAD

**Issue by marcomasa** [ros-planning/navigation2#2574]
## Bug report

**Required Info:**

- Operating System:   Ubuntu 20.04
- ROS2 Version: Galactic (apt-get)
- Version or commit hash:
ros-galactic-nav2-amcl	1.0.6-1focal.20210701.002235
ros-galactic-nav2-behavior-tree	1.0.6-1focal.20210701.002952
ros-galactic-nav2-bringup	1.0.6-1focal.20210701.015912
ros-galactic-nav2-bt-navigator	1.0.6-1focal.20210701.004934
ros-galactic-nav2-common	1.0.6-1focal.20210630.232638
ros-galactic-nav2-controller	1.0.6-1focal.20210701.004401
ros-galactic-nav2-core	1.0.6-1focal.20210701.004136
ros-galactic-nav2-costmap-2d	1.0.6-1focal.20210701.002823
ros-galactic-nav2-dwb-controller	1.0.6-1focal.20210701.005251
ros-galactic-nav2-lifecycle-manager	1.0.6-1focal.20210701.002253
ros-galactic-nav2-map-server	1.0.6-1focal.20210701.002229
ros-galactic-nav2-msgs	1.0.6-1focal.20210630.235639
ros-galactic-nav2-navfn-planner	1.0.6-1focal.20210701.004410
ros-galactic-nav2-planner	1.0.6-1focal.20210701.004411
ros-galactic-nav2-recoveries	1.0.6-1focal.20210701.004929
ros-galactic-nav2-regulated-pure-pursuit-controller	1.0.6-1focal.20210701.004418
ros-galactic-nav2-rviz-plugins	1.0.6-1focal.20210701.014516
ros-galactic-nav2-smac-planner	1.0.6-1focal.20210701.004430
ros-galactic-nav2-util	1.0.6-1focal.20210701.001550
ros-galactic-nav2-voxel-grid	1.0.6-1focal.20210701.002338
ros-galactic-nav2-waypoint-follower	1.0.6-1focal.20210701.004452

- DDS implementation: default

#### Steps to reproduce issue

use big maps without outer boundaries

#### Expected behavior

a valid path that doesnt jump from one mapside to the other

#### Actual behavior

The path, instead of following the map layout through sometimes non-free costs, just jumps to the other side of the map.

<img width="586" alt="nav2 path bug" src="https://user-images.githubusercontent.com/38527619/134989088-8cdb3b03-cee2-4485-bc50-c7c7369e1bae.PNG">

#### Additional information

I guess this is caused by array access in C++. Maybe while searching for neighbors and jumping to the next matrice line?

Solution suggestion: add a distance check between each pose of a path

**Comment by SteveMacenski** [comment]
Please provide more details. Config files, which of the smac planner's youre using, etc.

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/blob/main/nav2_smac_planner/src/node_2d.cpp#L140

Basically just needs a simple check here if the `i` is wrapped around on X or Y. Should just be a couple of `if` checks.

**Comment by marcomasa** [comment]
Thanks for the quick response!

Yes, it is the 2D version, as i want to get paths for omnidirectional robots.

Parameters for the global planner:
```
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      use_final_approach_orientation: True
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.5                     # tolerance for planning if unable to reach exact pose, in meters, for 2D node
      downsample_costmap: false           # whether or not to downsample the map
      downsampling_factor: 1          # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      allow_unknown: false                # allow traveling in unknown space
      max_iterations: 1000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000    # maximum number of iterations to attempt to reach goal once in tolerance, 2D only
      max_planning_time: 3.5              # max time in s for planner to plan, smooth, and upsample. Will scale maximum smoothing and upsampling times based on remaining time after planning.
      motion_model_for_search: "MOORE"    # 2D Moore, Von Neumann; Hybrid Dubin, Redds-Shepp; State Lattice set internally
      cost_travel_multiplier: 2.0         # For 2D: Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
      angle_quantization_bins: 64         # For Hybrid/Lattice nodes: Number of angle bins for search, must be 1 for 2D node (no angle search)
      analytic_expansion_ratio: 3.5       # For Hybrid/Lattice nodes: The ratio to attempt analytic expansions during search for final approach.
      minimum_turning_radius: 0.01      # For Hybrid/Lattice nodes: minimum turning radius in m of path / vehicle
      reverse_penalty: 1.0                # For Reeds-Shepp model: penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.01                # For Hybrid/Lattice nodes: penalty to apply if motion is changing directions, must be >= 0
      non_straight_penalty: 1.0          # For Hybrid/Lattice nodes: penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 1.7                   # For Hybrid/Lattice nodes: penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      lattice_filepath: ""                # For Lattice node: the filepath to the state lattice graph
      lookup_table_size: 20               # For Hybrid/Lattice nodes: Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: True      # For Hybrid/Lattice nodes: Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1e-10
```

Global Costmap:
```
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      #robot_radius: 0.22
      footprint: '[[0.24,0.2],[0.24,-0.2],[-0.24,-0.2],[-0.24,0.2]]'
      resolution: 0.025
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True
```
