### ISSUE TITLE
Resolve all ros2_dependencies into their respective mainlines, release, or overlay into navigation2

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#275]
We need to be able to do this to run in the build farm CI as part of ticket #99 

Specifically 
- [x] ros2_message_filters
- [x] ros2/launch
- [x] xmlrpcpp
- [ ] behavior_tree_core
- [ ] angles

```
  ros2_message_filters:
    type: git
    url: https://github.com/intel/ros2_message_filters.git
    version: master
  ros2/launch:
    type: git
    url: https://github.com/crdelsey/launch.git
    version: TimerActionWorkaround
  xmlrpcpp:
    type: git
    url: https://github.com/bpwilcox/xmlrpcpp.git
    version: master
  behavior_tree_core:
    type: git
    url: https://github.com/mjeronimo/BehaviorTree.CPP
    version: master


```
