### ISSUE TITLE
Recovery Backup Not Triggering

### ISSUE THREAD

**Issue by philmurp** [ros-planning/navigation2#2771]
Hello, I am running Foxy install of ROS2/Nav2 stack with Mecanum, NVIDIA Jetson computer. I used Linorobot2 as install setup, Navigation YAML: [LINK](https://github.com/linorobot/linorobot2/blob/1ebfae81ea741ac4d0ee6024eebe26c2f1e329f3/linorobot2_navigation/config/navigation.yaml)

When my robot is stuck in a corner, I see it enters the recovery tree and does the spin and wait actions; however it has never performed the backup function and as a result it usually ends up aborting after a few tries and I have to restart the entire navigation stack.

Based on the Nav2 documentation it looks all pretty default for the parameters for recovery server so not sure why it wont try backup when it tries spin and wait pretty well

If it does abort is there any reason that I need to completely restart the entire Nav stack, rather than it being able to accept a new goal?

**Comment by SteveMacenski** [comment]
Your hyperlink doesn't render. 

Do you see logging associated with the backup, perhaps with an error saying that is was unable to due to a collision? 

I know in early days there was an issue where the default configuration file incorrectly in foxy said `back_up` instead of `backup` which messed with the topic names. Try `ros2 topic list` and see if you have both. If so, there was a misconfiguration

**Comment by philmurp** [comment]
Updated the LINK so hopefully it shows up now. 

Looking at the file:

One line for plugins says:
`recovery_plugins: ["spin", "back_up", "wait"]`

Another line says:
```
    back_up:
      plugin: "nav2_recoveries/BackUp"
```

So should it be "BackUp" in both places instead of "back_up" in the recovery_plugins line?

To your other question: Have never seen backup even come up in the loggin, it shows spin and wait and then aborts, never seen backup in any logs.

**Comment by SteveMacenski** [comment]
Does your behavior tree include a backup call? Many don't have it even. The backup would only be triggered if your behavior tree uses it. 

You should check the topics like I requested - I don't remember off hand which caps/underscores we used in Foxy. It's changed a few times.

**Comment by philmurp** [comment]
Bottom of post is my full topic list, recoveries_server is the only relevant topic I believe, and in the .yaml file this is what is within that server:

As I mentioned above I see mismatch of "back_up" in the plugins vs below "BackUp"
```
recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "back_up", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    back_up:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2 
```



Full topic list:
```
ros2 topic list
/amcl/transition_event
/amcl_pose
/bt_navigator/transition_event
/camera/depth/color/points
/cmd_vel
/controller_server/transition_event
/cost_cloud
/diagnostics
/evaluation
/global_costmap/clearing_endpoints
/global_costmap/costmap
/global_costmap/costmap_raw
/global_costmap/costmap_updates
/global_costmap/footprint
/global_costmap/global_costmap/transition_event
/global_costmap/published_footprint
/goal_pose
/imu/data
/initialpose
/joint_states
/local_costmap/clearing_endpoints
/local_costmap/costmap
/local_costmap/costmap_raw
/local_costmap/costmap_updates
/local_costmap/footprint
/local_costmap/local_costmap/transition_event
/local_costmap/published_footprint
/local_plan
/map
/map_server/transition_event
/marker
/odom
/odom/unfiltered
/parameter_events
/particle_cloud
/particlecloud
/plan
/planner_server/transition_event
/received_global_plan
/recoveries_server/transition_event
/robot_description
/rosout
/scan
/set_pose
/tf
/tf_static
/transformed_global_plan
/waypoint_follower/transition_event
/zed/point_cloud/cloud_registered
```
