### ISSUE TITLE
[very minor] misspelling in readme

### ISSUE THREAD

**Issue by kimsooyoung** [ros-planning/navigation2#2775]
## Tiny misspelling in readme of smac_planner parameters

Now I'm reading all documents about Nav2, And find some tiny spelling error.

During [nav2_smac_planner - parameters](https://github.com/ros-planning/navigation2/tree/main/nav2_smac_planner#parameters)

```
      smooth_path: True                   # For Lattice/Hybrid ndoes: Whether or not to smooth the path, always true for 2D nodes.
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
```

I think `For Lattice/Hybrid **ndoes**` should be changed to `For Lattice/Hybrid **nodes**`

By the way, This is the **nicest** ros package I've ever seen.
So much thank you and hope to stay safe!
