### ISSUE TITLE
[global costmap]footprint dose not work with the inflationLayer

### ISSUE THREAD

**Issue by chinabbz** [ros-planning/navigation2#2825]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - galactic

#### Steps to reproduce issue

```
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 5.0
      resolution: 0.5
      track_unknown_space: true
      footprint: "[[2.25,0.75],[2.25,-0.75],[-2.25,-0.75],[-2.25,0.75]]"
```
```
inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0 
        inflation_radius: 0.55
```
#### Expected behavior
The footprint will work with inflationLayer
#### Actual behavior
The footprint does not work, because the path is so closed to the inflation layer
![屏幕截图 2022-02-18 15:56:18](https://user-images.githubusercontent.com/47048080/154641806-38b5b3b2-6338-49a9-b23a-7f40e96862bd.png)

#### Additional information
But when I remove the inflationLayer(only staticLayer), the footprint worked:
![2](https://user-images.githubusercontent.com/47048080/154642402-3c0d2888-fb33-42d7-b42e-120bb2b22a95.png)
