### ISSUE TITLE
SmacPlannerLattice doesn't exist in nav2_smac_planner

### ISSUE THREAD

**Issue by omerts** [ros-planning/navigation2#2951]
## Bug report

**Required Info:**

- Operating System:
  - Ubunut 20.04
- ROS2 Version:
  - Galactic
- Version or commit hash:
  - ros-galactic-navigation2        1.0.8-1focal.20220430.173751
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
Add the following nav2_params.yaml configuration for the planner server
``` 
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ['GridBased']
    GridBased:
      plugin: 'nav2_smac_planner/SmacPlannerLattice'
```

#### Expected behavior
Planner server node should be initialized successfully.

#### Actual behavior
[planner_server-9] [FATAL] [1652619100.086530989] [planner_server]: Failed to create global planner. Exception: According to the loaded plugin descriptions the class nav2_smac_planner/SmacPlannerLattice with base class type nav2_core::GlobalPlanner does not exist. Declared types are  nav2_navfn_planner/NavfnPlanner nav2_smac_planner/SmacPlanner2D nav2_smac_planner/SmacPlannerHybrid
#### Additional information
Tried different configuration also using the same exact config as on the SmacPlannerLattice doc, and nothing helped
