### ISSUE TITLE
planner GridBased is not a valid planner error

### ISSUE THREAD

**Issue by RDaneelOlivav** [ros-planning/navigation2#2987]
## Bug report

When using a custom created plugin, in the planner server the only name accepted for the plugin is "GridBased". If any other name is used, such as for example "GridBasedCustom", the following error is triggered:

`planner GridBased is not a valid planner. Planner names are: GridBasedCustom`

But it also happens if we use the default plugin for planning ( see example bellow).

**Required Info:**

- Operating System: UBuntu 20
- ROS2 Version: Galactic
- Version or commit hash: galactic apt install
- DDS implementation: Default for galactic

#### Steps to reproduce issue
Add in the e`planner_server.yaml`the following code:

```
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True    
    planner_plugins: ["GridBasedCustom"]    
    GridBasedCustom:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
```

#### Expected behavior

I would expect that it would behave as the costmap plugins that we can set the name we want.

#### Actual behavior

It only works if we use the name ' GridBased' for the plugin

#### Additional information

Have a try following the tutorial: [PLanner Plugin tutorial](https://navigation.ros.org/plugin_tutorials/docs/writing_new_nav2planner_plugin.html)

But changing the name
----
## Feature request

Be able to use whatever name we want
