### ISSUE TITLE
RPP planner strange behaviour in reverse

### ISSUE THREAD

**Issue by jainRAV** [ros-planning/navigation2#3086]
## Bug report

**Required Info:**

- Operating System:
  - Docker 20.04 Ubuntu
- ROS2 Version:
  - rolling
- Version or commit hash:
  - latest 97068787fb35894a098f9c4600b5a06c7dddf43b
- DDS implementation:
  - rmw_cyclonedds_cpp

#### Steps to reproduce issue

Setting **use_rotate_to_heading**: false and **allow_reversing**: true

```
  FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.8
      lookahead_dist: 0.4
      min_lookahead_dist: 0.4
      max_lookahead_dist: 0.8
      lookahead_time: 1.0
      rotate_to_heading_angular_vel: 0.5
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: false
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 0.8
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: false
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.2
      use_rotate_to_heading: false
      allow_reversing: true
      rotate_to_heading_min_angle: 0.785 #45degree
      max_angular_accel: 0.5
      max_robot_pose_search_dist: 10.0
      use_interpolation: false
```
![gif](https://user-images.githubusercontent.com/80730146/180432213-369ab72a-8c7b-4861-b0b7-f54a00091836.gif)

#### Expected behavior
Robot to follow path in reverse (backward motion)
#### Actual behavior
Robot rotate completely and follow the path in strange fashion (as shown in gif above)
#### Additional information
In gif, the face with additional frame at front is _front_.
