### ISSUE TITLE
Humble - ClearEntireCostmap plugin not disabling global and local costmap

### ISSUE THREAD

**Issue by kamakshijain** [ros-planning/navigation2#3263]
Hello,
Project Statement: Robot will be interacting with an object (physically touching the object) present in the environment after T + 10 mins (example). 
Basically, the object at start time is part of the world and thus considered as an obstacle by costmap. After T + 10 mins when I want to interact with the object, I don't want it to be considered as an obstacle.

Trying to Use Plugin:  
ClearEntireCostmap plugin (and similar costmap manipulation plugins) for both globalcostmap and localcostmap. Follow up on #3243 in humble.

> I just did a quick test on rolling / main and things are working fine at least there. I localized the robot into an incorrect spot a few times so I created alot of scatter in the costmap. Then I called the service /global_costmap/clear_entirely_global_costmap service using the ros2 CLI and I can see that the scatter is removed.

I was able to verify what Steve Macenski tested on rolling. **I was able to clear the costmap for old scatter generated by wrong initialization, however I was not able to clear costmap for scatter generated for current position [for global costmap only].**
**Question 1: is it suppose to clear/disable costmap for current time? In ROS1: setting the costmap enable parameter to false, completely disabled costmap, I am looking for that kind of feature.**

WANTING: to Disable costmap at run-time, can I do that using this or some other service?

Issue2: I was not able to see any difference when I used service call ClearEntireCostmap for local costmap. There was no difference between before and after.

Please see the attached picture.
Picture contains, navigation logs, cmd line service call to global and local costmap and rviz.
```ros2 service call /global_costmap/clear_entirely_global_costmap nav2_msgs/srv/ClearEntireCostmap "{request: {}}" ```or
```ros2 service call /local_costmap/clear_entirely_local_costmap nav2_msgs/srv/ClearEntireCostmap "{request: {}}"```

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  -  humble
- Version or commit hash:
  - 1.1.2
![humble](https://user-images.githubusercontent.com/47581462/199590217-256ef4e2-2151-49db-9059-566113a221dd.png)

  
- DDS implementation:
  - rmw_cyclonedds_cpp

#### Steps to reproduce issue
1. using humble 1.1.2
2. ```export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp```
``` echo $RMW_IMPLEMENTATION```
3. ```ros2 service call /global_costmap/clear_entirely_global_costmap nav2_msgs/srv/ClearEntireCostmap "{request: {}}"```

#### Expected behavior

Global Costmap: 
Before:
![wrongg](https://user-images.githubusercontent.com/47581462/199591117-24968f12-7a0c-4bf0-b551-4d7c63da7710.png)
After:
![Screenshot from 2022-11-02 16-17-02](https://user-images.githubusercontent.com/47581462/199594018-70e552c6-eac2-43b4-b3c9-85035d7beb25.png)

#### Actual behavior
Global Costmap
Before: ![wrongg](https://user-images.githubusercontent.com/47581462/199591380-78ff1eab-49be-4490-a995-38eacd7c79d9.png)
After: 
![wronggafter](https://user-images.githubusercontent.com/47581462/199591379-fa75f274-89fa-4f33-bb26-5b3cc68129a0.png)

##Issue 2:
Local Costmap no change
![beforelocal](https://user-images.githubusercontent.com/47581462/199589523-7d95541c-83e4-4858-b34a-2f0aabcf9d0e.png)
![beforelocal](https://user-images.githubusercontent.com/47581462/199589576-38e8d212-b66b-4c6f-a4d0-73123dcb7700.png)

#### Additional information
Added nav2_config
```
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.22
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True
 ```

----
## Feature request
Disable Global and Local Costmap at Run-Time.
#### Feature description
ROS1 was able to set enable parameter to false and the costmap would get disabled at run-time. expecting something similar to be able to interact with objects in the environment.
