### ISSUE TITLE
SMAC lattice planner does not work properly for differential/rectangular robot.

### ISSUE THREAD

**Issue by Yousseflah** [ros-planning/navigation2#3342]
## Bug report

**Required Info:**

- Operating System: **Ubuntu 22.04**
  - 
- ROS2 Version: **Humble**
  - 
- Version or commit hash: **1.1.3 (from binaries)**
  - 
- DDS implementation:**rmw_cyclonedds**
  - 

#### Steps to reproduce issue:
**_I am not sure if this is a bug or not !_**
Send goal to the robot with opposite orientation while allowing the reverse option
I am using RPP as controller with SMAC lattice planner, here is my params for the planner:
```
planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerLattice"
      allow_unknown: true  
      tolerance: 0.05
      max_iterations: 1000000         
      max_on_approach_iterations: 1000  
      max_planning_time: 5.0          
      analytic_expansion_ratio: 3.5 
      analytic_expansion_max_length: 4.0 
      reverse_penalty: 1.0 
      change_penalty: 0.05 
      non_straight_penalty: 1.05
      cost_penalty: 2.0
      rotation_penalty: 1.0               
      retrospective_penalty: 0.015
      lattice_filepath: "path_to_file/output.json" 
      lookup_table_size: 20.0  
      cache_obstacle_heuristic: true
      allow_reverse_expansion: true
      smooth_path: False
```
and for the primitive config:

```
{
    "motion_model": "diff",
    "turning_radius": 1.0,
    "grid_resolution": 0.05,
    "stopping_threshold": 5,
    "num_of_headings": 16
}
```

#### Expected behavior
Robot to navigate in reverse mode, reach goal and rotate to the requested orientation.

#### Actual behavior
Robot is parking as a vehicle when it approaches the goal to meet the requested orientation.

![Screenshot from 2022-12-21 21-28-32](https://user-images.githubusercontent.com/53279766/209856232-37a608bb-847a-49a3-b312-7ff7431e0a34.png)

#### Additional information
Not sure if this is a bug or not, but it seems that the generated path is for ackermann even if `"motion_model": "diff"` in the config.
