### ISSUE TITLE
DWBLocalPlanner: NavToPose fails if prune_plan is disabled

### ISSUE THREAD

**Issue by DylanDeCoeyer-Quimesis** [ros-planning/navigation2#3375]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04.1 LTS
- ROS2 Version:
  - Humble
- Version or commit hash:
  - 1.1.5
- DDS implementation:
  - Fast DDS

#### Steps to reproduce issue
Set the DWBLocalPlanner parameters as follow:
```
prune_plan: False
prune_distance: 0.5
```
Set the dimensions of local costmap as follow:
```
width: 8
height: 8
```
Perform a NavToPose using DWBLocalPlanner as path follower, to a goal set at ~10m.

#### Expected behavior
The robot drives to the goal.

#### Actual behavior
The robot drives a few meters (~4, i.e. the half size of the local costmap), then stops. The following error message is displayed: 
```
[controller_server]: Resulting plan has 0 poses in it.
```
#### Additional information

----

**Comment by SteveMacenski** [comment]
Is this not a rolling costmap?

**Comment by DylanDeCoeyer-Quimesis** [comment]
```
controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["PositionAndOrientationGoalChecker"]
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 15.0
    # Goal checker parameters
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
    PositionAndOrientationGoalChecker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      shorten_transformed_plan: True
      prune_plan: True
      prune_distance: 0.5
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 1.0
      max_vel_y: 0.0
      max_vel_theta: 0.5
      min_speed_xy: 0.0
      max_speed_xy: 1.0
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 0.15
      acc_lim_y: 0.0
      acc_lim_theta: 0.3
      decel_lim_x: -0.45
      decel_lim_y: 0.0
      decel_lim_theta: -0.5
      vx_samples: 5
      vy_samples: 2
      vtheta_samples: 20
      sim_time: 1.5
      discretize_by_time: True
      time_granularity: 0.5
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["KinematicCritic", "GoalDistCritic", "PathDistCritic", "PathAlignCritic"]
      GoalDistCritic.scale: 12.0
      PathDistCritic.scale: 24.0
      PathDistCritic.aggregation_type: "product"
      PathAlignCritic.forward_point_distance: 0.5
      PathAlignCritic.scale: 32.0
      PathAlignCritic.aggregation_type: "product"
      KinematicCritic.scale: 1.0
      KinematicCritic.minimal_turning_radius: 1.5
```
```
local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 8
      height: 8
      resolution: 0.05
      footprint: "[ [0.496, 0.433], [0.496, -0.433], [-0.312, -0.433], [-0.312, 0.433] ]"
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.713
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: false
        footprint_clearing_enabled: true
        min_obstacle_height: 0.08
        max_obstacle_height: 1.5
        observation_sources: pointcloudL pointcloudR
        pointcloudL:
          data_type: PointCloud2
          topic: /camera_left/depth/color/points
          min_obstacle_height: -0.50
          max_obstacle_height: 3.00
          obstacle_min_range: 0.1
          obstacle_max_range: 8.0
          raytrace_min_range: 0.0
          raytrace_max_range: 9.0
          clearing: true
          marking: true
        pointcloudR:
          data_type: PointCloud2
          topic: /camera_right/depth/color/points
          min_obstacle_height: -0.50
          max_obstacle_height: 3.00
          obstacle_min_range: 0.1
          obstacle_max_range: 8.0
          raytrace_min_range: 0.0
          raytrace_max_range: 9.0
          clearing: true
          marking: true
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False
```
