### ISSUE TITLE
AMCL Couldn't determine robot's pose associated with laser scan

### ISSUE THREAD

**Issue by Jayden-F** [ros-planning/navigation2#3390]
## Bug report

**Required Info:**

- Operating System:
Ubuntu 20.04
- ROS2 Version:
Galactic Binaries
- Version or commit hash:
1.0.12-1focal.20221208.082109

- DDS implementation:
Cyclone

#### Steps to reproduce issue
Start localization_launch.py 
Give Initial pose close to actual location.

#### Expected behavior
Robot will be localized in map.

#### Actual behavior
Robot is localized close to its position then will continue to throw the following error Couldn't determine robot's pose associated with laser scan.

**Comment by SteveMacenski** [comment]
Provide the literal error and your configuration please. Can you reproduce with nav2_bringup or on another platform?

**Comment by Jayden-F** [comment]
The Error is: Couldn't determine robot's pose associated with laser scan. I will supply a log file ASAP. 

I will also note that the robot I am using is a namespaced turtlebot4.

# This is my current configuration. 

## localization.launch.py 
```
import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from nav2_common.launch import RewrittenYaml


def generate_launch_description():

    # rviz_config = os.path.join(get_package_share_directory(
    #     'localization_server'), 'config', 'localization_rviz_config.rviz')
    amcl_yaml = os.path.join(get_package_share_directory(
        'localization_server'), 'config', 'amcl_config.yaml')
    map_file = os.path.join(get_package_share_directory(
        'localization_server'), 'maps', 'box.yaml')

    ARGUMENTS = [
        DeclareLaunchArgument(
            'namespace',
            default_value='',
            description='Robot namespace'),

        DeclareLaunchArgument('use_sim_time', default_value='false',
                              choices=['true', 'false'],
                              description='Use sim time')
    ]

    namespace = LaunchConfiguration('namespace')
    use_sim_time = LaunchConfiguration('use_sim_time')

    param_substitutions = {
        'use_sim_time': use_sim_time}

    configured_params = RewrittenYaml(
        source_file=amcl_yaml,
        root_key=namespace,
        param_rewrites=param_substitutions,
        convert_types=True)

    remappings = [
        ("/tf", "tf"),
        ("/tf_static", "tf_static")]
    # ("/map", "map"),
    # ("/scan", "scan"),
    # ("/amcl_pose", "amcl_pose")]

    map_server = Node(
        package='nav2_map_server',
        namespace=namespace,
        executable='map_server',
        name='map_server',
        output='screen',
        remappings=remappings,
        parameters=[{'use_sim_time': use_sim_time},
                    {'yaml_filename': map_file}]
    )

    amcl_server = Node(
        package='nav2_amcl',
        namespace=namespace,
        executable='amcl',
        name='amcl_server',
        remappings=remappings,
        output='screen',
        parameters=[configured_params]
    )

    lifecycle_manager = Node(
        package='nav2_lifecycle_manager',
        namespace=namespace,
        executable='lifecycle_manager',
        name='lifecycle_manager_localization',
        output='screen',
        parameters=[{'use_sim_time': use_sim_time},
                    {'autostart': True},
                    {'bond_timeout': 0.0},
                    {'node_names': ['map_server', "amcl_server"]}]
    )

    ld = LaunchDescription(ARGUMENTS)
    ld.add_action(map_server)
    ld.add_action(amcl_server)
    ld.add_action(lifecycle_manager)
    return ld

```


## amcl_config.yaml 
```
amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    map_frame_id: "map"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
```
