### ISSUE TITLE
Feature request: costmap binary filter able to change ros parameters 

### ISSUE THREAD

**Issue by enricosutera** [ros-planning/navigation2#3511]
Hi, what about having the costmap binary filter (or a new one) capable of setting ros parameters along with publishing on a topic?
Some possible use cases: 
- enabling or disabling an obstacle layer source marking or clearing in a specific environment (e.g. infrared proximity sensors in a black environment)
- enabling or disabling full costmap layers (e.g. when going from indoor to pedestrian area).

I realize this can easily be done creating a third part node that subscribes to the currently available topic and modifies the parameter itself or directly having the callback in the node to which the parameter belongs. However I think this would be more flexible and decoupled to have all this is a configuration file!

**Comment by SteveMacenski** [comment]
@AlexeyMerzlyakov

**Comment by enricosutera** [comment]
I'd  also go with O2 because there would be the flexibility to change parameters also outside the costmap2D.

For what concerns non boolean values, I agree it could be useful, for instance speed limit filter could be replaced as long as max speed is a parameter changeable dynamically. Anyway this could be done later on!

I can work on this btw

**Comment by AlexeyMerzlyakov** [comment]
@enricosutera, thank you for taking the interest in this topic! Agree with O2 strategy to use service name as ROS-param for the Binary Filter. The PR is welcoming :blush:

**Comment by SteveMacenski** [comment]
Any update? Its been about a month!

**Comment by enricosutera** [comment]
Hi! Unfortunately I haven't a solution ready. I had very little time and I have an issue with using the `.../set_parameters` service.
Service calls fail (I did it with rclcpp first, but it's the same with ros2cli):
```
ros2 service call /global_costmap/global_costmap/set_parameters_atomically  rcl_interfaces/srv/SetParametersAtomically   '{parameters: [{name: "static_layer.enabled"}]}'
requester: making request: rcl_interfaces.srv.SetParametersAtomically_Request(parameters=[rcl_interfaces.msg.Parameter(name='static_layer.enabled', value=rcl_interfaces.msg.ParameterValue(type=0, bool_value=False, integer_value=0, double_value=0.0, string_value='', byte_array_value=[], bool_array_value=[], integer_array_value=[], double_array_value=[], string_array_value=[]))])

response:
rcl_interfaces.srv.SetParametersAtomically_Response(result=rcl_interfaces.msg.SetParametersResult(successful=False, reason='cannot undeclare a statically typed parameter'))
```
I have no idea why setting a parameter would require to undeclare it, anyway I think this is related to this old issue https://github.com/ros2/rclcpp/issues/1762 

Also I've tried using `rclcpp::SyncParametersClient` as in the [demos](https://github.com/ros2/demos/blob/rolling/demo_nodes_cpp/src/parameters/set_and_get_parameters.cpp) 
But again I encountered [known issues](https://github.com/ros2/rclcpp/issues/1553).

Naturally It works fine using `ros2 param` so I'll probably take a look at how it operates

**Comment by AlexeyMerzlyakov** [comment]
@enricosutera, the reason of such issue is seems that you are note specifying the value of parameter, and this parameter is treated to be unset.
As I understand, the intention is to support boolean `True/False` trigger support which could be specified directly via `boolean` type of ROS-parameter. Something like:
```
ros2 service call /global_costmap/global_costmap/set_parameters_atomically  rcl_interfaces/srv/SetParametersAtomically   '{parameters: [{name: "static_layer.enabled", value: {type: 1, bool_value: False}}]}'
ros2 service call /global_costmap/global_costmap/set_parameters_atomically  rcl_interfaces/srv/SetParametersAtomically   '{parameters: [{name: "static_layer.enabled", value: {type: 1, bool_value: True}}]}'
```
works for me

**Comment by enricosutera** [comment]
Thank you @AlexeyMerzlyakov , the issue was really that simple.

As for configuration, does something like this make sense for you?
I'm not sure whether to handle parameters separately or grouped by threshold.

Option 1: custom default state and flip threshold for each parameter
```
      binary_filter:

        plugin: "nav2_costmap_2d::BinaryFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
        transform_tolerance: 0.1
        default_state: False
        binary_state_topic: "/binary_state"
        flip_threshold: 50.0
        parameters: Param0 Param1 Param2
        Param0:
          node_name: "node_0"
          param_name: "param.sub_param"
          default_state: False
          flip_threshold: 50.0
        Param1:
          node_name: "node_1"
          param_name: "param.sub_param"
          default_state: True
          flip_threshold: 25.0
        Param2:
          node_name: "node_2"
          param_name: "param.sub_param"
          default_state: False
          flip_threshold: 75.0
```

Option2: common flip_threshold (in this case one should define two different istances of the filter in case different threshold were desired)
```
      binary_filter:

        plugin: "nav2_costmap_2d::BinaryFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
        transform_tolerance: 0.1
        default_state: False
        binary_state_topic: "/binary_state"
        flip_threshold: 50.0
        parameters: Param0 Param1 Param2
        Param0:
          node_name: "node_0"
          param_name: "param.sub_param"
          default_state: False
        Param1:
          node_name: "node_1"
          param_name: "param.sub_param"
          default_state: True
        Param2:
          node_name: "node_2"
          param_name: "param.sub_param"
          default_state: False
```
An alternative could be grouoing by threshold (that could correspond to map "zones"):

```
      binary_filter:

        plugin: "nav2_costmap_2d::BinaryFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
        transform_tolerance: 0.1
        default_state: False
        binary_state_topic: "/binary_state"
        flip_threshold: 50.0
        parameters: Thresh0 Thresh1
        Thresh0:
          nodes:       [node1,   node1,    node2]
          parameters: [param1,param2,  param1]    
          default_state: False
          flip_threshold: 50.0    
        Thresh1:
          nodes:       [node1,   node2,    node2]
          parameters: [param3,param2,  param3]    
          default_state: False
          flip_threshold: 60.0    

```
