### ISSUE TITLE
Range sensor layer topic name automatic adding prefix

### ISSUE THREAD

**Issue by Lannister-Xiaolin** [ros-planning/navigation2#3517]
## Bug report

**Required Info:**

- Operating System:
Ubuntu 20.04
- ROS2 Version:
galactic

#### Steps to reproduce issue

setting range sensor layer param as below shows:
```
      range_sensor_layer:
        plugin: "nav2_costmap_2d::RangeSensorLayer"
        enabled: True
        topics: ["collision_range"]
        mark_threshold: 0.7
        inflate_cone: 0.99
```

#### Expected behavior
Subscribe to topic:  collision_range
#### Actual behavior
Subscribe to topic:  /global_costmap/collision_range
#### Additional information

----
