### ISSUE TITLE
[velocity_smoother] Setting max_accel to negative flips sign of output

### ISSUE THREAD

**Issue by Aposhian** [ros-planning/navigation2#3520]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu
- ROS2 Version:
  - humble
- Version or commit hash:
  - https://github.com/fireflyautomatix/navigation2/tree/rpp-dubins-constraint-humble-backport
- DDS implementation:
  - CycloneDDS

#### Steps to reproduce issue
Set 
```yaml
velocity_smoother:
  ros__parameters:
    min_velocity: [0.0, 0.0, -1.0]
    max_accel: [-1.0, 0.0, 0.0]
```

#### Expected behavior
Error to be thrown?

#### Actual behavior
Positive commanded velocity results in negative smoothed velocity, ignoring velocity limits
![image](https://user-images.githubusercontent.com/16969110/228982170-124b1925-2477-4f88-9463-4404bb58405d.png)

#### Additional information
I think there are two action items here:
- apply max and min limits last
- throw if signs on accel, decel don't make sense, on both configure, and dynamic parameters callback
