### ISSUE TITLE
[planner_server][controller_server] Costmaps are Namespaced

### ISSUE THREAD

**Issue by AntoBrandi** [ros-planning/navigation2#3541]
In the `planner_server` and `controller_server`, when instantiating the Global and the Local costmap they are namespaced

Here the two instructions
https://github.com/ros-planning/navigation2/blob/4aaefad1162d5edcba26878cdb4a2f11322ada99/nav2_controller/src/controller_server.cpp#L63-L71

https://github.com/ros-planning/navigation2/blob/4aaefad1162d5edcba26878cdb4a2f11322ada99/nav2_planner/src/planner_server.cpp#L63-L70

These makes the two nodes have the following names 

```
>>> ros2 node list | grep costmap
/global_costmap/global_costmap
/local_costmap/local_costmap
```

And thus when setting the configuration parameters for the Global and Local costmap we need to set also the namespace

```
global_costmap:
  global_costmap:
    ros__parameters:
      footprint_padding: 0.03
      update_frequency: 1.0
      ...
```

Is there any reason to keep these namespaces? Is it possible to uniform these node's names to the same convention used for the other nodes? 

```
>>> ros2 node list
/amcl
/behavior_server
/bt_navigator
```

And set the parameters without namespacing them?

```
planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
```
