### ISSUE TITLE
DWA:  local planner crash into obstacle 

### ISSUE THREAD

**Issue by joeldushouyu** [ros-planning/navigation2#3594]
## Background
Currently, I am working on an autonomous lawn mower. 
Thus, in my configuration of the nav2 file (see below),
 
1. For the global cost map, I only added "static_layer", which basically the information that is published by the map server
The goal of the project is
The goal of the project is to do a coverage planning that covers all areas in the map (published by the map server) except those obstacle that are marked in the map image, which will reflect in the static_map. 
Thus, if I add the obstacle and inflation layers into my global map, those obstacle marks will still exist inside my global costmap, even after they are gone. So for example, if there is a person in front of the robot, if the robot is able to find a path to avoid the person, the global planner will do it. However, that place (where the person stands) will still be marked as an obstacle in the global cost map, until a cost map clear command is called. 
Moreover, during normal operation of the robot, the robot will rarely encounter any obstacles (both static and dynamic) since it runs on an open pasture.

3. For this simulation, I let the map server publish a white image, which represents that there is no obstacle in the static map. (This explains why the global planner path, blue line, will plan a straight path.
4. For the local cost map, I configured both obstacle( by the lidar) and inflation layer. I have double check that the local costmap updates correctly of the obstacles. 

## Bug report

**Required Info:**

- Operating System:
 Ubuntun 20.04
- ROS2 Version:
  - Galactic binary
- Version or commit hash:
ros-galactic-navigation2	1.0.12-1focal.20221208.082109

- DDS implementation:
  -default option in ros2 galactic (not sure what is that )

#### Steps to reproduce issue
1. launch a robot in gazebo
2. use nav2_bringup_launch with params_file: configure to the parameter file below.

navigation parameter
```yaml

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.26
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 2.5
      acc_lim_y: 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.12
      #footprint: "[ [0.21, 0.195], [0.21, -0.195], [-0.21, -0.195], [-0.21, 0.195] ]"
      plugins: [ "inflation_layer", "obstacle_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      robot_radius: 0.3
      resolution: 0.05
      track_unknown_space: false
      static_map: false
      rolling_window: false
      width: 10
      height: 10
      origin_x: -5.0
      origin_y: -5.0
      track_unknown_space: true
      plugins: ["static_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "/home/shouyu/nav2_ws/src/fishbot/src/fishbot_navigation2/maps/fishbot_map.yaml"

# map_saver:
#   ros__parameters:
#     use_sim_time: True
#     save_map_timeout: 5.0
#     free_thresh_default: 0.25
#     occupied_thresh_default: 0.65
#     map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
```
```

```

#### Expected behavior

Although the global cost map only has a static layer and planned a path across the obstacle.
I am expecting the dwa (local planner) will be able to stop in front of the obstacle, and maybe perform some recovery behavior instead of hitting the obstacle.

#### Actual behavior
![error3](https://github.com/ros-planning/navigation2/assets/65317431/6bb0078a-17d0-4583-a2d1-f27e7f56610d)

In the picture, the blue line represent the global path planner and the brown line represent the local path planner.

Log from nav2:
```bash
[INFO] [launch]: All log files can be found below /home/shouyu/.ros/log/2023-06-02-15-04-28-656139-shouyu-Nitro-AN515-55-120769
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [map_server-1]: process started with pid [120834]
[INFO] [lifecycle_manager-2]: process started with pid [120836]
[INFO] [controller_server-3]: process started with pid [120839]
[INFO] [planner_server-4]: process started with pid [120841]
[INFO] [recoveries_server-5]: process started with pid [120843]
[INFO] [bt_navigator-6]: process started with pid [120845]
[INFO] [waypoint_follower-7]: process started with pid [120847]
[INFO] [lifecycle_manager-8]: process started with pid [120850]
[planner_server-4] [INFO] [1685732669.847865450] [planner_server]: 
[planner_server-4] 	planner_server lifecycle node launched. 
[planner_server-4] 	Waiting on external lifecycle transitions to activate
[planner_server-4] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-6] [INFO] [1685732669.849533163] [bt_navigator]: 
[bt_navigator-6] 	bt_navigator lifecycle node launched. 
[bt_navigator-6] 	Waiting on external lifecycle transitions to activate
[bt_navigator-6] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-6] [INFO] [1685732669.849662049] [bt_navigator]: Creating
[map_server-1] [INFO] [1685732669.850010673] [map_server]: 
[map_server-1] 	map_server lifecycle node launched. 
[map_server-1] 	Waiting on external lifecycle transitions to activate
[map_server-1] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-1] [INFO] [1685732669.850107612] [map_server]: Creating
[planner_server-4] [INFO] [1685732669.854799788] [planner_server]: Creating
[lifecycle_manager-2] [INFO] [1685732669.856414517] [lifecycle_manager_localization]: Creating
[lifecycle_manager-2] [INFO] [1685732669.858869386] [lifecycle_manager_localization]: Creating and initializing lifecycle service clients
[lifecycle_manager-8] [INFO] [1685732669.861737071] [lifecycle_manager_navigation]: Creating
[waypoint_follower-7] [INFO] [1685732669.864014819] [waypoint_follower]: 
[waypoint_follower-7] 	waypoint_follower lifecycle node launched. 
[waypoint_follower-7] 	Waiting on external lifecycle transitions to activate
[waypoint_follower-7] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-7] [INFO] [1685732669.865712985] [waypoint_follower]: Creating
[controller_server-3] [INFO] [1685732669.869149326] [controller_server]: 
[controller_server-3] 	controller_server lifecycle node launched. 
[controller_server-3] 	Waiting on external lifecycle transitions to activate
[controller_server-3] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-8] [INFO] [1685732669.876172389] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[lifecycle_manager-2] [INFO] [1685732669.877700637] [lifecycle_manager_localization]: Starting managed nodes bringup...
[lifecycle_manager-2] [INFO] [1685732669.877749425] [lifecycle_manager_localization]: Configuring map_server
[controller_server-3] [INFO] [1685732669.887380444] [controller_server]: Creating controller server
[planner_server-4] [INFO] [1685732669.904350733] [global_costmap.global_costmap]: 
[planner_server-4] 	global_costmap lifecycle node launched. 
[planner_server-4] 	Waiting on external lifecycle transitions to activate
[planner_server-4] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-4] [INFO] [1685732669.910263068] [global_costmap.global_costmap]: Creating Costmap
[lifecycle_manager-8] [INFO] [1685732669.915298609] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-8] [INFO] [1685732669.919314680] [lifecycle_manager_navigation]: Configuring controller_server
[recoveries_server-5] [INFO] [1685732669.935586309] [recoveries_server]: 
[recoveries_server-5] 	recoveries_server lifecycle node launched. 
[recoveries_server-5] 	Waiting on external lifecycle transitions to activate
[recoveries_server-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-3] [INFO] [1685732669.998618033] [local_costmap.local_costmap]: 
[controller_server-3] 	local_costmap lifecycle node launched. 
[controller_server-3] 	Waiting on external lifecycle transitions to activate
[controller_server-3] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-3] [INFO] [1685732670.002528085] [local_costmap.local_costmap]: Creating Costmap
[map_server-1] [INFO] [1685732670.015965143] [map_server]: Configuring
[map_server-1] [INFO] [map_io]: Loading yaml file: /home/shouyu/nav2_ws/install/fishbot_navigation2/share/fishbot_navigation2/maps/zeroCost.yaml
[map_server-1] [DEBUG] [map_io]: resolution: 0.05
[map_server-1] [DEBUG] [map_io]: origin[0]: -3.35
[map_server-1] [DEBUG] [map_io]: origin[1]: -2.95
[map_server-1] [DEBUG] [map_io]: origin[2]: 0
[map_server-1] [DEBUG] [map_io]: free_thresh: 0.25
[map_server-1] [DEBUG] [map_io]: occupied_thresh: 0.65
[map_server-1] [DEBUG] [map_io]: mode: trinary
[map_server-1] [DEBUG] [map_io]: negate: 0
[map_server-1] [INFO] [map_io]: Loading image_file: /home/shouyu/nav2_ws/install/fishbot_navigation2/share/fishbot_navigation2/maps/zeroCost.png
[map_server-1] [DEBUG] [map_io]: Read map /home/shouyu/nav2_ws/install/fishbot_navigation2/share/fishbot_navigation2/maps/zeroCost.png: 134 X 118 map @ 0.05 m/cell
[lifecycle_manager-2] [INFO] [1685732670.030231214] [lifecycle_manager_localization]: Activating map_server
[map_server-1] [INFO] [1685732670.030627259] [map_server]: Activating
[map_server-1] [INFO] [1685732670.030794526] [map_server]: Creating bond (map_server) to lifecycle manager.
[controller_server-3] [INFO] [1685732670.037240901] [controller_server]: Configuring controller interface
[controller_server-3] [INFO] [1685732670.038332136] [controller_server]: getting goal checker plugins..
[controller_server-3] [INFO] [1685732670.038609618] [controller_server]: Controller frequency set to 10.0000Hz
[controller_server-3] [INFO] [1685732670.038656405] [local_costmap.local_costmap]: Configuring
[controller_server-3] [INFO] [1685732670.050793539] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-3] [INFO] [1685732670.065206037] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[controller_server-3] [INFO] [1685732670.065395447] [local_costmap.local_costmap]: Using plugin "obstacle_layer"
[controller_server-3] [INFO] [1685732670.068018048] [local_costmap.local_costmap]: Subscribed to Topics: scan
[controller_server-3] [INFO] [1685732670.080333747] [local_costmap.local_costmap]: Initialized plugin "obstacle_layer"
[controller_server-3] [INFO] [1685732670.091079183] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-3] [INFO] [1685732670.102510184] [controller_server]: Created goal checker : general_goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-3] [INFO] [1685732670.124692163] [controller_server]: Controller Server has general_goal_checker  goal checkers available.
[controller_server-3] [INFO] [1685732670.130680618] [controller_server]: Created controller : FollowPath of type dwb_core::DWBLocalPlanner
[controller_server-3] [INFO] [1685732670.134470259] [controller_server]: Setting transform_tolerance to 0.200000
[lifecycle_manager-2] [INFO] [1685732670.136975346] [lifecycle_manager_localization]: Server map_server connected with bond.
[lifecycle_manager-2] [INFO] [1685732670.137040161] [lifecycle_manager_localization]: Managed nodes are active
[lifecycle_manager-2] [INFO] [1685732670.137062557] [lifecycle_manager_localization]: Creating bond timer...
[controller_server-3] [INFO] [1685732670.176283881] [controller_server]: Using critic "RotateToGoal" (dwb_critics::RotateToGoalCritic)
[controller_server-3] [INFO] [1685732670.182435389] [controller_server]: Critic plugin initialized
[controller_server-3] [INFO] [1685732670.183297506] [controller_server]: Using critic "Oscillation" (dwb_critics::OscillationCritic)
[controller_server-3] [INFO] [1685732670.185184856] [controller_server]: Critic plugin initialized
[controller_server-3] [INFO] [1685732670.185653160] [controller_server]: Using critic "BaseObstacle" (dwb_critics::BaseObstacleCritic)
[controller_server-3] [INFO] [1685732670.189472854] [controller_server]: Critic plugin initialized
[controller_server-3] [INFO] [1685732670.190212421] [controller_server]: Using critic "GoalAlign" (dwb_critics::GoalAlignCritic)
[controller_server-3] [INFO] [1685732670.192034220] [controller_server]: Critic plugin initialized
[controller_server-3] [INFO] [1685732670.193014348] [controller_server]: Using critic "PathAlign" (dwb_critics::PathAlignCritic)
[controller_server-3] [INFO] [1685732670.194032610] [controller_server]: Critic plugin initialized
[controller_server-3] [INFO] [1685732670.194376065] [controller_server]: Using critic "PathDist" (dwb_critics::PathDistCritic)
[controller_server-3] [INFO] [1685732670.194913439] [controller_server]: Critic plugin initialized
[controller_server-3] [INFO] [1685732670.195206190] [controller_server]: Using critic "GoalDist" (dwb_critics::GoalDistCritic)
[controller_server-3] [INFO] [1685732670.195661387] [controller_server]: Critic plugin initialized
[controller_server-3] [INFO] [1685732670.195692421] [controller_server]: Controller Server has FollowPath  controllers available.
[lifecycle_manager-8] [INFO] [1685732670.200745729] [lifecycle_manager_navigation]: Configuring planner_server
[planner_server-4] [INFO] [1685732670.200993671] [planner_server]: Configuring
[planner_server-4] [INFO] [1685732670.201034803] [global_costmap.global_costmap]: Configuring
[planner_server-4] [INFO] [1685732670.209802799] [global_costmap.global_costmap]: Using plugin "static_layer"
[planner_server-4] [INFO] [1685732670.219771451] [global_costmap.global_costmap]: Subscribing to the map topic (/map) with transient local durability
[planner_server-4] [INFO] [1685732670.222245287] [global_costmap.global_costmap]: Initialized plugin "static_layer"
[planner_server-4] [INFO] [1685732670.226437295] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 134 X 118 at 0.050000 m/pix
[planner_server-4] [INFO] [1685732670.238065154] [planner_server]: Created global planner plugin GridBased of type nav2_navfn_planner/NavfnPlanner
[planner_server-4] [INFO] [1685732670.238182443] [planner_server]: Configuring plugin GridBased of type NavfnPlanner
[planner_server-4] [INFO] [1685732670.261225860] [planner_server]: Planner Server has GridBased  planners available.
[lifecycle_manager-8] [INFO] [1685732670.292767568] [lifecycle_manager_navigation]: Configuring recoveries_server
[recoveries_server-5] [INFO] [1685732670.293094419] [recoveries_server]: Configuring
[recoveries_server-5] [INFO] [1685732670.307778197] [recoveries_server]: Creating recovery plugin spin of type nav2_recoveries/Spin
[recoveries_server-5] [INFO] [1685732670.311548695] [recoveries_server]: Configuring spin
[recoveries_server-5] [INFO] [1685732670.327342730] [recoveries_server]: Creating recovery plugin backup of type nav2_recoveries/BackUp
[recoveries_server-5] [INFO] [1685732670.329703189] [recoveries_server]: Configuring backup
[recoveries_server-5] [INFO] [1685732670.334099837] [recoveries_server]: Creating recovery plugin wait of type nav2_recoveries/Wait
[recoveries_server-5] [INFO] [1685732670.340671169] [recoveries_server]: Configuring wait
[lifecycle_manager-8] [INFO] [1685732670.351144213] [lifecycle_manager_navigation]: Configuring bt_navigator
[bt_navigator-6] [INFO] [1685732670.351449140] [bt_navigator]: Configuring
[lifecycle_manager-8] [INFO] [1685732670.501959427] [lifecycle_manager_navigation]: Configuring waypoint_follower
[waypoint_follower-7] [INFO] [1685732670.502278083] [waypoint_follower]: Configuring
[waypoint_follower-7] [INFO] [1685732670.530452748] [waypoint_follower]: Created waypoint_task_executor : wait_at_waypoint of type nav2_waypoint_follower::WaitAtWaypoint
[lifecycle_manager-8] [INFO] [1685732670.531532269] [lifecycle_manager_navigation]: Activating controller_server
[controller_server-3] [INFO] [1685732670.531712968] [controller_server]: Activating
[controller_server-3] [INFO] [1685732670.531745143] [local_costmap.local_costmap]: Activating
[controller_server-3] [INFO] [1685732670.531760261] [local_costmap.local_costmap]: Checking transform
[controller_server-3] [INFO] [1685732670.531848842] [local_costmap.local_costmap]: start
[controller_server-3] [INFO] [1685732670.532497232] [controller_server]: Creating bond (controller_server) to lifecycle manager.
[lifecycle_manager-8] [INFO] [1685732670.636177337] [lifecycle_manager_navigation]: Server controller_server connected with bond.
[lifecycle_manager-8] [INFO] [1685732670.636376012] [lifecycle_manager_navigation]: Activating planner_server
[planner_server-4] [INFO] [1685732670.637030311] [planner_server]: Activating
[planner_server-4] [INFO] [1685732670.637149421] [global_costmap.global_costmap]: Activating
[planner_server-4] [INFO] [1685732670.637175054] [global_costmap.global_costmap]: Checking transform
[planner_server-4] [INFO] [1685732670.637397613] [global_costmap.global_costmap]: start
[planner_server-4] [INFO] [1685732670.687515533] [planner_server]: Activating plugin GridBased of type NavfnPlanner
[planner_server-4] [INFO] [1685732670.687626308] [planner_server]: Creating bond (planner_server) to lifecycle manager.
[lifecycle_manager-8] [INFO] [1685732670.791566800] [lifecycle_manager_navigation]: Server planner_server connected with bond.
[lifecycle_manager-8] [INFO] [1685732670.791635144] [lifecycle_manager_navigation]: Activating recoveries_server
[recoveries_server-5] [INFO] [1685732670.791961742] [recoveries_server]: Activating
[recoveries_server-5] [INFO] [1685732670.791994854] [recoveries_server]: Activating spin
[recoveries_server-5] [INFO] [1685732670.792008216] [recoveries_server]: Activating backup
[recoveries_server-5] [INFO] [1685732670.792018928] [recoveries_server]: Activating wait
[recoveries_server-5] [INFO] [1685732670.792029420] [recoveries_server]: Creating bond (recoveries_server) to lifecycle manager.
[lifecycle_manager-8] [INFO] [1685732670.899317622] [lifecycle_manager_navigation]: Server recoveries_server connected with bond.
[lifecycle_manager-8] [INFO] [1685732670.899372650] [lifecycle_manager_navigation]: Activating bt_navigator
[bt_navigator-6] [INFO] [1685732670.899765124] [bt_navigator]: Activating
[bt_navigator-6] [INFO] [1685732671.082756280] [bt_navigator]: Creating bond (bt_navigator) to lifecycle manager.
[lifecycle_manager-8] [INFO] [1685732671.190165403] [lifecycle_manager_navigation]: Server bt_navigator connected with bond.
[lifecycle_manager-8] [INFO] [1685732671.190248389] [lifecycle_manager_navigation]: Activating waypoint_follower
[waypoint_follower-7] [INFO] [1685732671.190709386] [waypoint_follower]: Activating
[waypoint_follower-7] [INFO] [1685732671.190776328] [waypoint_follower]: Creating bond (waypoint_follower) to lifecycle manager.
[lifecycle_manager-8] [INFO] [1685732671.298612698] [lifecycle_manager_navigation]: Server waypoint_follower connected with bond.
[lifecycle_manager-8] [INFO] [1685732671.298789764] [lifecycle_manager_navigation]: Managed nodes are active
[lifecycle_manager-8] [INFO] [1685732671.298836793] [lifecycle_manager_navigation]: Creating bond timer...
[bt_navigator-6] [INFO] [1685732771.238115991] [bt_navigator]: Begin navigating from current location to (1.85, 1.56)
[controller_server-3] [INFO] [1685732771.259388106] [controller_server]: Received a goal, begin computing control effort.
[controller_server-3] [WARN] [1685732771.259508469] [controller_server]: No goal checker was specified in parameter 'current_goal_checker'. Server will use only plugin loaded general_goal_checker . This warning will appear once.
[controller_server-3] [INFO] [1685732772.360298407] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732773.360296927] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732774.360277174] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732775.460282457] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732776.460288323] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732777.461623407] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732778.460293331] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732779.560303031] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732780.560336794] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732781.560278129] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732782.660385974] [controller_server]: Passing new path to controller.
[controller_server-3] [INFO] [1685732783.666008406] [controller_server]: Passing new path to controller.


```

#### Things I have tried
1. I have double check that the local cost map does update properly by adding/deleting object from gazebo
2. The footprint of the robot is bigger that the robot model (as shown in the video above)
3. I have tried to increase the inflation layer in local costmap to 1.6, which did not help to solve the issue
4. 

----
