### ISSUE TITLE
error_code_names parameter for BT Navigator plugins

### ISSUE THREAD

**Issue by RBT22** [ros-planning/navigation2#3633]
#### Feature description

It would be nice to have the option to give different `error_code_names` parameters to BT Navigator plugins. Currently you can pass only one list to the parent node and that is used in every navigator. This new customization option would help to handle structually more different navigators.

#### Implementation considerations

In the config file the `error_code_name` parameter for the navigator could be placed near the plugin:
```
bt_navigator:
  ros__parameters:
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
      error_code_names:
        - compute_path_error_code
        - follow_path_error_code
```
We can reach the parent node's parameters in the BtActionServer implementation, so my proposal would be to use these new values as default and fallback on the parent node's values, and if those are not set also, we could use the default.

This way the parameter can be declared as "<navigator_name>.error_code_names". One question is how to get the first part of this string in the BtActionServer. We have `action_name`, which is "task/<navigator_name>" so technically we could take the second part of it, but maybe there is a better way.
