### ISSUE TITLE
Planner quantize paths in one direction and not the other in UTM coordinates

### ISSUE THREAD

**Issue by alexanderjyuen** [ros-planning/navigation2#3712]
- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Humble
- DDS implementation:
  - CycloneDDS

I am experiencing a behavior where when I try to generate a path, using either the `navigate_through_poses_w_replanning_and_recovery.xml` or `navigate_to_pose_w_replanning_and_recovery.xml
` behavior trees, I get a plan that is quantized at 0.5m in the Y direction of map frame but not in the X direction of map frame. The image below shows an example of this, where the grids are set to 0.5m:

![quantization](https://github.com/ros-planning/navigation2/assets/103065090/bcb0581b-6cb0-457d-b74a-190ce2fa4efb).

I've tested this using the ThetaStarPlanner, Smac2DPlanner, and HybridA and the same behavior occurs for al lthree planners. Below is my global costmap parameters:

```
global_costmap:
  global_costmap:
    ros__parameters:
      
      footprint: "[[-1.0, -1.4], [-1.0, 1.4], [4.0, 1.4], [4.0, -1.4]]"
      footprint_padding: 0.0
      transform_tolerance: 0.3
      
      update_frequency: 10.0
      publish_frequency: 1.0

      global_frame: utm
      robot_base_frame: base_link

      width: 700
      height: 700
      origin_x: -350.0
      origin_y: -350.0
      resolution: 0.1
      
      rolling_window: false
  
      track_unknown_space: false
      unknown_cost_value: 25

      # plugins: ["obstacle_layer", "inflation_layer"]
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        enabled: false
        subscribe_to_updates: true
        transform_tolerance: 0.1
        map_topic: "/map"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: "front_scan_filtered front_scan" # add front_scan when unlocking costmaps
        front_scan_filtered:
          data_type: LaserScan
          topic: /front_lidar/scan
          marking: false # Set this to True to start using it to generate obstacles
          clearing: true # Set this to True to make sure it is also used for clearing
          inf_is_valid: false # Leave this as False because we don't want infinites to be costmaps! 
          observation_persistence: 1.0
          min_obstacle_height: -10.0
          max_obstacle_height: 15.0
          obstacle_min_range: 0.0
          obstacle_max_range: 18.0
          raytrace_min_range: 0.0 
          raytrace_max_range: 20.0 # With a bigger raytrace than obstacle range we should clear infinites
        # Uncomment below to turn on infinite clearing
        front_scan: 
          data_type: LaserScan
          topic: /front_lidar/scan
          marking: false # Set this to False, We don't want to mark from infinite
          clearing: true # Set tihs to True, we want to use infinites to clear! 
          inf_is_valid: true # We want to use infinites for clearing
          min_obstacle_height: 0.0
          max_obstacle_height: 15.0
          obstacle_min_range: 0.0
          obstacle_max_range: 18.0
          raytrace_min_range: 0.0 
          raytrace_max_range: 20.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 0.3
        inflation_radius: 0.01
        
      always_send_full_costmap: True
```
As shown above I have a global costmap resolution of 0.1, in the image provide it looks like in one direction the points are at spaced at about 0.1m (5 to a grid) but in the other direction it snaps to the grid at 0.5m. 

Has anyone seen this behavior and is there a known solution?
