### ISSUE TITLE
Extrapolation Error for base_link to map transform when attempting to navigate

### ISSUE THREAD

**Issue by alexanderjyuen** [ros-planning/navigation2#3741]
- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - humble
- DDS implementation:
  - CycloneDDS

I am currently getting an issue where when I send a goal and the robot executes the `navigate_to_pose_w_replanning_and_recovery.xml` behavior tree, the navigation stack will plan for a little bit and fail after a few seconds stating  that there is an extrapolation error going from base_link to map:

```
[bt_navigator-11] [INFO] [1691190455.879684352] [bt_navigator]: Begin navigating from current location to (32.05, 0.66)
[controller_server-7] [INFO] [1691190455.902021074] [controller_server]: Received a goal, begin computing control effort.
[controller_server-7] [WARN] [1691190455.902143493] [controller_server]: No goal checker was specified in parameter 'current_goal_checker'. Server will use only plugin loaded goal_checker . This warning will appear once.
[controller_server-7] [INFO] [1691190456.202368477] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190456.402344674] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190456.602343989] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190456.902363239] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190457.102360323] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190457.302356449] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190457.502344812] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190457.802352587] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190458.002359233] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190458.202346588] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190458.502353400] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190458.702350913] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190458.902364877] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190459.202360847] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190459.402344543] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190459.602350023] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190459.802350522] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190460.102342919] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190460.302358895] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190460.502361328] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190460.802409924] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190461.002351572] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190461.202346480] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190461.502369100] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190461.702352011] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190461.902365604] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190462.102344006] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190462.402346614] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190462.602355085] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190462.802356741] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190463.102346333] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190463.302399887] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190463.502343559] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190463.802374738] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190464.002364775] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190464.202352729] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190464.402341106] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190464.702344989] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190464.902370424] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190465.102360291] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190465.402376914] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190465.602354681] [controller_server]: Passing new path to controller.
[controller_server-7] [INFO] [1691190465.802349595] [controller_server]: Passing new path to controller.
[planner_server-9] [ERROR] [1691190470.997915737] [transformPoseInTargetFrame]: Extrapolation Error looking up target frame: Lookup would require extrapolation into the past.  Requested time 1691190455.798790 but the earliest data is at time 1691190460.996669, when looking up transform from frame [base_link] to frame [map]
[planner_server-9] 
[planner_server-9] [WARN] [1691190470.998032704] [planner_server]: Could not transform the start or goal pose in the costmap frame
[planner_server-9] [WARN] [1691190470.998157375] [planner_server]: [compute_path_to_pose] [ActionServer] Aborting handle.
[planner_server-9] [INFO] [1691190471.010150866] [global_costmap.global_costmap]: Received request to clear entirely the global_costmap
[controller_server-7] [INFO] [1691190471.102362349] [controller_server]: Passing new path to controller.
[controller_server-7] [ERROR] [1691190471.103126134] [controller_server]: Invalid path, Path is empty.
```
In our setup we have a global EKF publishing that base_link to map transform at 50Hz and the local EKF publishing the base_link to odom transform at 60Hz, with both EKFs being `robot_localization`. So it seems strange that we would be without a base_link to map transform for more than 5 seconds. The pose is sent to Navigation 2 via RVIZ and the parameter_bridge by opening up rviz with `rosrun rviz rviz /move_base_simple/goal:=/goal_pose`. 

I've also done a `ros2 topic hz` on the outputs of `navsat`, `global EKF,` and `local EKF`, to check if nothing is skipping a beat and it looks like they are publishing at the specified rates

Has anyone experienced this issue before? The following are what I believe to be relevant configurations:

**Global Costmap:**
```
global_costmap:
  global_costmap:
    ros__parameters:
      footprint: "[[-1.1,-2.4],[-1.1,2.4],[5.3,2.4],[5.3,-2.4]]"
      footprint_padding: 0.2
      transform_tolerance: 5.0

      update_frequency: 10.0
      publish_frequency: 1.0

      global_frame: map
      robot_base_frame: base_link

      width: 100
      height: 100
      origin_x: 0.0
      origin_y: 0.0
      resolution: 0.5
      rolling_window: true

      track_unknown_space: false
      unknown_cost_value: 25

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: "right_scan right_scan_filtered left_scan left_scan_filtered"

        right_scan_filtered:
          data_type: LaserScan
          topic: /right_lidar/scan
          marking: true
          clearing: true
          inf_is_valid: false
          min_obstacle_height: -0.1
          max_obstacle_height: 20.0
          obstacle_min_range: 0.0
          obstacle_max_range: 20.0
          raytrace_min_range: 0.0
          raytrace_max_range: 5.0
        right_scan:
          data_type: LaserScan
          topic: /right_lidar/scan
          marking: false
          clearing: true
          inf_is_valid: true
          min_obstacle_height: -0.1
          max_obstacle_height: 20.0
          obstacle_min_range: 0.0
          obstacle_max_range: 20.0
          raytrace_min_range: 0.0
          raytrace_max_range: 20.0
        left_scan_filtered:
          data_type: LaserScan
          topic: /left_lidar/scan
          marking: true
          clearing: true
          inf_is_valid: false
          min_obstacle_height: -0.1
          max_obstacle_height: 20.0
          obstacle_min_range: 0.0
          obstacle_max_range: 20.0
          raytrace_min_range: 0.0
          raytrace_max_range: 5.0
        left_scan:
          data_type: LaserScan
          topic: /left_lidar/scan
          marking: false
          clearing: true
          inf_is_valid: true
          min_obstacle_height: -0.1
          max_obstacle_height: 20.0
          obstacle_min_range: 0.0
          obstacle_max_range: 20.0
          raytrace_min_range: 0.0
          raytrace_max_range: 20.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 0.3
        inflation_radius: 1.0

      always_send_full_costmap: True
```
**Planner Server:**
```
planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: True
      allow_unknown: True
      tolerance: 3.0
```
**navigate_to_pose_w_replanning_and_recovery.xml**
```
<!--
  This Behavior Tree replans the global path periodically at 1 Hz and it also has
  recovery actions specific to planning / control as well as general system issues.
  This will be continuous if a kinematically valid planner is selected.
-->
<root main_tree_to_execute="MainTree">
  <BehaviorTree ID="MainTree">
    <RecoveryNode number_of_retries="6" name="NavigateRecovery">
      <PipelineSequence name="NavigateWithReplanning">
        <PlannerSelector selected_planner="{selected_planner}" default_planner="GridBased" topic_name="planner_selector"/>
        <RateController hz="5.0">
          <RecoveryNode number_of_retries="1" name="ComputePathToPose">
            <ComputePathToPose goal="{goal}" path="{path}" planner_id="{selected_planner}"/>
            <ClearEntireCostmap name="ClearGlobalCostmap-Context" service_name="global_costmap/clear_entirely_global_costmap"/>
          </RecoveryNode>
        </RateController>
        <ControllerSelector selected_controller="{selected_controller}" default_controller="FollowPath" topic_name="controller_selector"/>
        <RecoveryNode number_of_retries="1" name="FollowPath">
          <FollowPath path="{path}" controller_id="{selected_controller}"/>
          <ClearEntireCostmap name="ClearLocalCostmap-Context" service_name="local_costmap/clear_entirely_local_costmap"/>
        </RecoveryNode>
      </PipelineSequence>
      <ReactiveFallback name="RecoveryFallback">
        <GoalUpdated/>
        <RoundRobin name="RecoveryActions">
          <Sequence name="ClearingActions">
            <ClearEntireCostmap name="ClearLocalCostmap-Subtree" service_name="local_costmap/clear_entirely_local_costmap"/>
            <ClearEntireCostmap name="ClearGlobalCostmap-Subtree" service_name="global_costmap/clear_entirely_global_costmap"/>
          </Sequence>
          <Spin spin_dist="1.57"/>
          <Wait wait_duration="5"/>
          <BackUp backup_dist="0.30" backup_speed="0.05"/>
        </RoundRobin>
      </ReactiveFallback>
    </RecoveryNode>
  </BehaviorTree>
</root>
```
**Global EKF Settings**
```
map_filter_node:
    ros__parameters:
      # For parameter descriptions, please refer to the template parameter files for each node.
      frequency: 50.0
      sensor_timeout: 0.1
      two_d_mode: true
      transform_time_offset: 0.0
      transform_timeout: 0.0
      print_diagnostics: true
      debug: false

      map_frame: map
      odom_frame: odom
      base_link_frame: base_link
      world_frame: map

```
**Local EKF Settings**
```
odom_filter_node:
    ros__parameters:
      # For parameter descriptions, please refer to the template parameter files for each node.
      frequency: 60.0
      sensor_timeout: 0.1
      two_d_mode: true
      transform_time_offset: 0.0
      transform_timeout: 0.0
      print_diagnostics: true
      debug: false

      map_frame: map
      odom_frame: odom
      base_link_frame: base_link
      world_frame: odom
```
