### ISSUE TITLE
Exception when running obstacle layer without message filters

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#386]
## Bug report

**Required Info:**

- Operating System:
  -Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - Latest as of Nov 28, 2018

#### Steps to reproduce issue
Run stack and configure the obstacle layer in local costmap. Here's an example parameter yaml file for that.

```yaml
local_costmap:
  ros__parameters:
    always_send_full_costmap: True
    observation_sources: scan
    scan:
      topic: scan
```

#### Actual behavior
Error messages of the form:

```
[ERROR] [nav2_costmap_2d]: TF Exception that should never happen for sensor frame: , cloud frame: base_scan, Lookup would require extrapolation into the future.  Requested time 15401.50800 but the latest data is at time 15401.50000, when looking up transform from frame [base_scan] to frame [map]
```
