### ISSUE TITLE
Static layer plugin ignores the map_topic parameter and reverts to default behaviour

### ISSUE THREAD

**Issue by sagarvl96** [ros-planning/navigation2#4107]
## Bug report

**Required Info:**

- Operating System:
     Ubuntu 22.04.3 LTS
- ROS2 Version:
     ROS2 Humble base docker
- Version or commit hash:
      ros-humble-navigation2  1.1.12-1jammy.20240126.081240
- DDS implementation:
       rmw_cyclonedds

#### Steps to reproduce issue
   ```
static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        map_topic: /refined_map
```
   Set the map_topic parameter of Static Layer to a custom map topic (/refined_map).

#### Expected behavior
    Subscribing to the map topic (/refined_map) with transient local durability

#### Actual behavior

Still subscribes to the global map topic (/map) and ignores the topic mentioned as a parameter
     `Subscribing to the map topic (/map) with transient local durability`
