### ISSUE TITLE
Switching between Planner Plugins in the Behavior Tree

### ISSUE THREAD

**Issue by ipa-dmo** [ros-planning/navigation2#5118]
Required Info:

    Operating System:
        Ubuntu 24 (in docker container)
    ROS2 Version:
        Jazzy
    Version or commit hash:
        jazzy
    DDS implementation:
        Cyclone
    Nav2 Package:
        - nav2_behavior_tree
        - nav2_planner
        - nav2_smac_planner
    Have you asked this on Robotics Stack Exchange?
        No

Hello,
we have a use case, where we want to drive with two different planner configurations/plugins. For some navigation tasks we want to allow the robot to plan and drive backwards (it could be needed as well to reach the goal) but for other following navigation tasks we want to disable it and force e.g. a minimal turning radius.

I created an small minimal example branch [here](https://github.com/ipa-dmo/navigation2/tree/test/switching_backwards_planning).

I would assume something like the following BT configuration (link: [here](https://github.com/ipa-dmo/navigation2/blob/test/switching_backwards_planning/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_changed_planners.xml)) would allow such a behavior.
The "GridBased" planner ID does not allow backward driving, but the "GridBased_reversing_enabled" does allow it. See nav2_params [here](https://github.com/ipa-dmo/navigation2/blob/test/switching_backwards_planning/nav2_bringup/params/nav2_params.yaml)

>  <BehaviorTree ID="MainTree">
    <PipelineSequence name="Navigate_4_goals">
      <ControllerSelector selected_controller="{selected_controller}" default_controller="FollowPath" topic_name="controller_selector"/>
      <GetGoalFromGoalsVector goals="{goals}" goal_index="0" goal="{goal}"/>
      <GetGoalFromGoalsVector goals="{goals}" goal_index="1" goal="{goal_2}"/>
      <GetGoalFromGoalsVector goals="{goals}" goal_index="2" goal="{goal_3}"/>
      <GetGoalFromGoalsVector goals="{goals}" goal_index="3" goal="{goal_4}"/>
      <PipelineSequence>
        <ComputePathToPose goal="{goal}" path="{path}" planner_id="GridBased" error_code_id="{compute_path_error_code}"/>
        <FollowPath path="{path}" controller_id="{selected_controller}" error_code_id="{follow_path_error_code}"/>
        <ComputePathToPose goal="{goal_2}" path="{path}" planner_id="GridBased_reversing_enabled" error_code_id="{compute_path_error_code}"/>
        <FollowPath path="{path}" controller_id="{selected_controller}" error_code_id="{follow_path_error_code}"/>
        <ComputePathToPose goal="{goal_3}" path="{path}" planner_id="GridBased" error_code_id="{compute_path_error_code}"/>
        <FollowPath path="{path}" controller_id="{selected_controller}" error_code_id="{follow_path_error_code}"/>
        <ComputePathToPose goal="{goal_4}" path="{path}" planner_id="GridBased_reversing_enabled" error_code_id="{compute_path_error_code}"/>
        <FollowPath path="{path}" controller_id="{selected_controller}" error_code_id="{follow_path_error_code}"/>
      </PipelineSequence>
    </PipelineSequence>    
  </BehaviorTree>

Would this be in general a viable approach? 

When running the example branch with `ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False` (replaced the default navigate through poses BT navigator to this BT configuration) with 4 Goals, as shown in the next screenshots, the robot allows backward driving for all intermediate goals after the first one.
Not only for the paths between 1->2 and 3->4 but also for 2->3, where backward driving should not be possible due to the DUBIN motion modell. 

Defining 4 Goals in directions, which would trigger backward driving.
![Image](https://github.com/user-attachments/assets/a3d0dd9a-6846-48f1-bd06-fd5062265316)

Driving to the first goal: 

![Image](https://github.com/user-attachments/assets/2ea5f6ff-805a-4d31-904f-3990dddc9980)

Driving to the second goal: Robot performes the allowed backward driving.

![Image](https://github.com/user-attachments/assets/e6a6c70b-02b9-49c2-974c-6101b6c9e1da)

Driving to the third goal: Robot still plans a path backwards, even though its planner_id should not allow this.

![Image](https://github.com/user-attachments/assets/4def27fe-d963-4461-b5ec-d155b9fe8730)

Driving to the fourth goal: Robot performes the allowed backward driving.

![Image](https://github.com/user-attachments/assets/517bf21a-832d-4af1-927d-532a798a007f)

But it does not only effect this behavior tree, but also future planing after successfully executing this behavior tree. When sending afterwards a new normal goal for the navigate_to_pose action, the robot still uses backward driving, even though the navigate_to_poaw action should use the "GridBased" planner instance with the DUBIN motion modell:

![Image](https://github.com/user-attachments/assets/5baebe4e-c219-4412-8091-6227cd7edde0)

In contrast, when sending a goal before executing the navigate_through_poses actions the planner does limit itself to forward driving.

Somehow for me it looks like, the planner ID does not update correctly inside the planner server.

**Comment by SteveMacenski** [comment]
This seems like BT XML that may have some issues. You're be calling simultaneously multiple follow path calls due to the nature of the pipeline sequence https://docs.nav2.org/behavior_trees/overview/nav2_specific_nodes.html#control-pipelinesequence and relying on essentially the next one preempting the `N` last ones that sent it to other goals with other paths. You'd also be computing alot of erroneous paths.  

You'd be better off with a more basic approach where you compute the path and send it to the controller. Before you do that, you can check which goal you're on. If you've achieved it, move to the next. In that case, check which Planner you should use and send it to the PlannerSelector to change the planners. You could probably do it a number of ways, but I don't think this method of using pipeline sequence is correct. Maybe a general sequence would work? But, it would be manually constrained to knowing the number of points in the goal vector to start with instead of enabling you to use any number of them.  

I'd suggest spending a bit of time and learning about how to format behavior trees, there are some good tutorials, papers, and books online which can help with this kind of thing! 😄

**Comment by ipa-dmo** [comment]
Yes, the Pipeline Sequence does not make much sense here. This XML should only show a minimal example of switching planner IDs.  The actual BT XML loops over a goal vector and is more complex. The issue we see, is that the selection of the `planner_id` does not work as I would expect.

Updated example:

```
<root BTCPP_format="4" main_tree_to_execute="MainTree">
  <BehaviorTree ID="MainTree">
    <Sequence name="Navigate_4_goals">
      <GetGoalFromGoalsVector goals="{goals}" goal_index="0" goal="{goal}"/>
      <GetGoalFromGoalsVector goals="{goals}" goal_index="1" goal="{goal_2}"/>
      <GetGoalFromGoalsVector goals="{goals}" goal_index="2" goal="{goal_3}"/>
      <GetGoalFromGoalsVector goals="{goals}" goal_index="3" goal="{goal_4}"/>
      <Sequence>
        <ComputePathToPose goal="{goal}" path="{path}" planner_id="GridBased" error_code_id="{compute_path_error_code}"/>
        <Wait wait_duration="10.0"/>
        <ComputePathToPose goal="{goal_2}" path="{path}" planner_id="GridBased_reversing_enabled" error_code_id="{compute_path_error_code}"/>
        <Wait wait_duration="10.0"/>
        <ComputePathToPose goal="{goal_3}" path="{path}" planner_id="GridBased" error_code_id="{compute_path_error_code}"/>
        <Wait wait_duration="10.0"/>
        <ComputePathToPose goal="{goal_4}" path="{path}" planner_id="GridBased_reversing_enabled" error_code_id="{compute_path_error_code}"/>
        <Wait wait_duration="10.0"/>
      </Sequence>
    </Sequence>    
  </BehaviorTree>
</root>
```

The first plan does not use backwards planning with `GridBased` config.
The second one allows it, with the `GridBased_reversing_enabled`.
Then the third should not allow it, by using again the `GridBased` config, but the planner does compute backward paths. (See image Path 3).

So switching from the one planner plugin to another one does work. But switching again/back seems not to work.

With these two planner configs:

```
GridBased:
      plugin: "nav2_smac_planner::SmacPlannerHybrid" # In Iron and older versions, "/" was used instead of "::"
      downsample_costmap: false           # whether or not to downsample the map
      downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      tolerance: 0.25                    # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
      allow_unknown: true                 # allow traveling in unknown space
      max_iterations: 1000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000    # Maximum number of iterations after within tolerances to continue to try to find exact solution
      max_planning_time: 5.0              # max time in s for planner to plan, smooth
      motion_model_for_search: "DUBIN"    # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 72         # Number of angle bins for search
      analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 10.0  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      analytic_expansion_max_cost: 200.0  # The maximum single cost for any part of an analytic expansion to contain and be valid, except when necessary on approach to goal
      analytic_expansion_max_cost_override: false  #  Whether or not to override the maximum cost setting if within critical distance to goal (ie probably required)
      minimum_turning_radius: 0.25        # minimum turning radius in m of path / vehicle
      reverse_penalty: 5.0                # Penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.0                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      non_straight_penalty: 1.2           # Penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 3.5                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      retrospective_penalty: 0.015
      lookup_table_size: 20.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: false     # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      debug_visualizations: false         # For Hybrid nodes: Whether to publish expansions on the /expansions topic as an array of poses (the orientation has no meaning) and the path's footprints on the /planned_footprints topic. WARNING: heavy to compute and to display, for debug only as it degrades the performance.
      use_quadratic_cost_penalty: False
      downsample_obstacle_heuristic: True
      allow_primitive_interpolation: False
      smooth_path: True                   # If true, does a simple and quick smoothing post-processing to the path
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2
```

```
GridBased_reversing_enabled:
      plugin: "nav2_smac_planner::SmacPlannerHybrid" # In Iron and older versions, "/" was used instead of "::"
      downsample_costmap: false           # whether or not to downsample the map
      downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      tolerance: 0.25                     # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
      allow_unknown: true                 # allow traveling in unknown space
      max_iterations: 1000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      max_on_approach_iterations: 1000    # Maximum number of iterations after within tolerances to continue to try to find exact solution
      max_planning_time: 5.0              # max time in s for planner to plan, smooth
      motion_model_for_search: "REEDS_SHEPP"    # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 72         # Number of angle bins for search
      analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
      analytic_expansion_max_length: 10.0  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
      analytic_expansion_max_cost: 200.0  # The maximum single cost for any part of an analytic expansion to contain and be valid, except when necessary on approach to goal
      analytic_expansion_max_cost_override: false  #  Whether or not to override the maximum cost setting if within critical distance to goal (ie probably required)
      minimum_turning_radius: 0.25        # minimum turning radius in m of path / vehicle
      reverse_penalty: 1.0                # Penalty to apply if motion is reversing, must be => 1
      change_penalty: 0.0                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
      non_straight_penalty: 1.2           # Penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 3.5                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      retrospective_penalty: 0.015
      lookup_table_size: 20.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: false     # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
      debug_visualizations: false         # For Hybrid nodes: Whether to publish expansions on the /expansions topic as an array of poses (the orientation has no meaning) and the path's footprints on the /planned_footprints topic. WARNING: heavy to compute and to display, for debug only as it degrades the performance.
      use_quadratic_cost_penalty: False
      downsample_obstacle_heuristic: True
      allow_primitive_interpolation: False
      smooth_path: True                   # If true, does a simple and quick smoothing post-processing to the path
      smoother:
        max_iterations: 1000
        w_smooth: 0.3
        w_data: 0.2
        tolerance: 1.0e-10
        do_refinement: true
        refinement_num: 2
```

And here are the path results:
First Path:

![Image](https://github.com/user-attachments/assets/2282e87d-ffb9-4451-84ab-165c1a212157)

Second Path:

![Image](https://github.com/user-attachments/assets/d134eabe-3a51-4b2e-a8f6-2a01128135ec)

Third Path:

![Image](https://github.com/user-attachments/assets/48139906-272e-4f08-bb22-83748b4a0ba0)

Forth Path:

![Image](https://github.com/user-attachments/assets/875611b0-a029-44dd-8864-de74446fa981)
