### ISSUE TITLE
Nav2 Humble:  transform_tolerance has not influence on  Controller Server

### ISSUE THREAD

**Issue by keshavchintamani** [ros-planning/navigation2#5234]
For context: we get a very high rate of  TF Extrapolation Errors from Controller Server when CPU temperatures spike causing the local controller to fail its Nav Goal 

**_Same time, the TF differences reported are small enough to ignore_** 

#### What I've Tried

Controller_Server does not provide its own Transform_Tolerance Param
and uses Costmap_2D's transform_tolerance AFAIK

This is extracted from controller_server.cpp (humble-main)

```
rclcpp::Duration tolerance(rclcpp::Duration::from_seconds(costmap_ros_->getTransformTolerance()));
  nav_2d_utils::transformPose(
    costmap_ros_->getTfBuffer(), costmap_ros_->getGlobalFrameID(),
    end_pose_, transformed_end_pose, tolerance);

```

I replicated the  call above in a watchdog node while our Nav2 stack was running. 

costmap_ros_->getTransformTolerance() always returns 0.3 which appears to be its default, even if our Nav2 
param yaml has transform_tolerance of 0.6 in both sections.

Bottom_line: Increasing the transform_tolerance in local_costmap and global_costmap has no influence. 
```
local_costmap:
 #other params 
      transform_tolerance: 0.6
```

```
global_costmap:
   #other params 
      transform_tolerance: 0.6
```

Am I missing something?

It isn't clear to me why controller_server  does not provide it's own transform_tolerance. 

https://docs.nav2.org/configuration/packages/configuring-controller-server.html#parameters

**Required Info:**

- Operating System: Ubuntu 22.04
- Computer:  Intel i5 (16GB) and i7 (32GB)
- ROS2 Version: Humble
- Version or commit hash:
- DDS implementation: Cyclone
- Nav2 Package: Controller_server

**Comment by SteveMacenski** [comment]
Huh, that shouldn't be happening. Transform tolerance isn't a 'special' parameter that is handled any way differently from others. It is obtained in the configure lifecycle transition, which should be completed by the time any controller server method is called which relies on it.

I added some print statements and see that the parameters are being properly read: 

```
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      transform_tolerance: 0.222222

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      transform_tolerance: 0.111111
```

```
[component_container_isolated-6] 0.222222
[component_container_isolated-6] 0.111111
```
