### ISSUE TITLE
Robot does not stop to change direction on cusp points [MPPI]

### ISSUE THREAD

**Issue by KKlimowicz-PIMOT** [ros-planning/navigation2#5303]
## Bug report
Might be related to nav2_mppi_controller behavior near sharp inflections in the global plan.

**Required Info:**

- Operating System:
  - Ubuntu 24.04 (running inside Docker)
- Computer:
  - i7-11700F
- ROS2 Version:
  - Jazzy
- Version or commit hash:
  - 28a560a3e38455589601e05cd397b7a47b5f68ec
- DDS implementation:
  - Eclypse Cyclone DDS

#### Steps to reproduce issue
Use a map and goal where the robot has to pass through a cusp (sharp change in curvature or reversal in motion).

#### Expected behavior
The robot should properly decelerate before the cusp point, reorient smoothly, and continue to the goal.

#### Actual behavior
Occasionally, when approaching a cusp point, the robot slows down but does not reorient or stop as expected. Instead, it drives past the cusp point and continues moving indefinitely without correcting its path or reaching the final goal.

#### Additional information

Sometimes robot will stop with message that goal was succeded but is far from that and it is not connected with goal checker because it has a lot smaller values (position tolerance 0.2m), than that seen on [this video](https://youtu.be/UsWVHBUcLyk).

Actual config:
```yaml
# Behavior Tree Navigator
bt_navigator:
    ros__parameters:
        enable_stamped_cmd_vel: true
        use_sim_time: True
        global_frame: map
        robot_base_frame: base_link
        odom_topic: /odom
        bt_loop_duration: 5  # Faster updates for dynamic goals (ms)
        default_server_timeout: 20  # Action server timeout (ms)
        default_nav_to_pose_bt_xml: $(find-pkg-share pawo_navigation)/behavior_trees/pawo.xml

behavior_server:
    ros__parameters:
        enable_stamped_cmd_vel: true

bt_navigator_navigate_through_poses_rclcpp_node:
    ros__parameters:
        enable_stamped_cmd_vel: true

        use_sim_time: True

bt_navigator_navigate_to_pose_rclcpp_node:
    ros__parameters:
        enable_stamped_cmd_vel: true

        use_sim_time: True


controller_server:
    ros__parameters:
        enable_stamped_cmd_vel: true
        use_sim_time: True
        controller_frequency: 40.0 
        min_x_velocity_threshold: 0.05
        min_theta_velocity_threshold: 0.05
        progress_checker_plugins: ["progress_checker"] # progress_checker_plugin: "progress_checker" For Humble and older
        goal_checker_plugins: ["general_goal_checker"]
        controller_plugins: ["FollowPath"]
        progress_checker:
            plugin: "nav2_controller::SimpleProgressChecker"
            required_movement_radius: 0.5
            movement_time_allowance: 10.0
        general_goal_checker:
            stateful: True
            plugin: "nav2_controller::SimpleGoalChecker"
            xy_goal_tolerance: 0.2
            yaw_goal_tolerance: 0.26
        FollowPath:
            plugin: "nav2_mppi_controller::MPPIController"
            time_steps: 80
            model_dt: 0.05      # The model_dt parameter generally should be set to the duration of your control frequency.
                                # So if your control frequency is 20hz, this should be 0.05. However, you may also set it lower but not larger.
                                # it helps to change maximum velocity
            batch_size: 3000
            vx_std: 0.9
            wz_std: 0.7
            vx_max: 2.0
            vx_min: -3.0
            wz_max: 1.6
            iteration_count: 1
            retry_attempt_limit: 2
            prune_distance: 25.0
            transform_tolerance: 0.1
            temperature: 0.3
            gamma: 0.015
            motion_model: "Ackermann"
            visualize: True
            enforce_path_inversion: true
            inversion_xy_tolerance: 0.2
            inversion_yaw_tolerance: 0.75
            AckermannConstraints:
                min_turning_r: 4.79
            TrajectoryVisualizer:
                trajectory_step: 30
                time_step: 10
            critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "VelocityDeadbandCritic", "NearGoalVelocityCritic"]
            NearGoalVelocityCritic:
                enabled: true
                cost_weight: 20.
                cost_power: 1
                threshold_to_consider: 2.5
            ConstraintCritic:
                enabled: true
                cost_weight: 2.0
                cost_power: 1
            GoalAngleCritic:
                enabled: true
                cost_weight: 13.0
                cost_power: 1
                threshold_to_consider: 1.5
            GoalCritic:
                enabled: true
                cost_weight: 15.0
                cost_power: 1
                threshold_to_consider: 1.5
            CostCritic:
                enabled: true
                cost_power: 1
                cost_weight: 3.81
                critical_cost: 300.0
                consider_footprint: true
                collision_cost: 1000000.0
                near_goal_distance: 0.5
            PathAlignCritic:
                enabled: true
                cost_weight: 10.0
                cost_power: 1
                threshold_to_consider: 1.0
                offset_from_furthest: 2
                max_path_occupancy_ratio: 0.07
                use_path_orientations: true
                trajectory_point_step: 4
            PathAngleCritic:
                enabled: true
                cost_weight: 2.2
                cost_power: 1
                threshold_to_consider: 2.0
                offset_from_furthest: 1
                max_angle_to_furthest: 0.0
                forward_preference: false
            PathFollowCritic:
                enabled: true
                cost_weight: 5.0
                cost_power: 1
                threshold_to_consider: 0.1
                offset_from_furthest: 1
            VelocityDeadbandCritic:
                enabled: false
                cost_power: 1
                cost_weight: 35.0
                deadband_velocities: [0.4, 0.05, 0.00]

global_costmap:
    global_costmap:
        ros__parameters:
            update_frequency: 2.0
            publish_frequency: 3.0
            width: 100
            height: 100
            origin_x: -50.0
            origin_y: -50.0
            rolling_window: true
            global_frame: map
            robot_base_frame: base_link
            use_sim_time: True
            footprint: "[ [2.53, -0.859], [2.53, 0.859], [-0.393, 0.859], [-0.393, -0.859] ]"
            resolution: 0.2             # need to be the same as in slam mapper or loading map
            track_unknown_space: false
            plugins: ["stvl_layer","inflation_layer"]
            inflation_layer:
                plugin: "nav2_costmap_2d::InflationLayer"
                cost_scaling_factor: 0.25
                inflation_radius: 10.5
            stvl_layer:
                plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
                enabled: true
                voxel_decay: 1.5
                decay_model: 0
                voxel_size: 0.25
                track_unknown_space: true
                unknown_threshold: 15
                mark_threshold: 1
                footprint_clearing_enabled: true
                update_footprint_enabled: true
                combination_method: 1
                origin_z: 0.0
                publish_voxel_map: true
                transform_tolerance: 0.2
                mapping_mode: false
                map_save_duration: 60.0
                observation_sources: pointcloud_mark pointcloud_clear
                pointcloud_mark:
                    data_type: PointCloud2
                    topic: /lidar_points_filtered
                    marking: true
                    clearing: false
                    obstacle_range: 50.0         # meters
                    min_obstacle_height: 0.1     # default 0, meters
                    max_obstacle_height: 2.0     # default 3, meters
                    expected_update_rate: 0.0    # default 0, if not updating at this rate at least, remove from buffer
                    observation_persistence: 0.0 # default 0, use all measurements taken during now-value, 0=latest
                    inf_is_valid: false          # default false, for laser scans
                    filter: "passthrough"        # default passthrough, apply "voxel", "passthrough", or no filter to sensor data, recommend on     
                    voxel_min_points: 0          # default 0, minimum points per voxel for voxel filter
                    clear_after_reading: true    # default false, clear the buffer after the layer gets readings from it
                pointcloud_clear:
                    enabled: true                #default true, can be toggled on/off with associated service call
                    data_type: PointCloud2
                    topic: /lidar_points_filtered
                    marking: false
                    clearing: true
                    max_z: 15.0                 # default 0, meters
                    min_z: 0.5                  # default 10, meters
                    vertical_fov_angle: 0.523   # default 0.7, radians. For 3D lidars it's the symmetric FOV about the planar axis.
                    vertical_fov_padding: 0.05  # 3D Lidar only. Default 0, in meters 
                    horizontal_fov_angle: 6.29  # 3D lidar scanners like the VLP16 have 360 deg horizontal FOV.
                    decay_acceleration: 5.0     # default 0, 1/s^2. 
                    model_type: 1               # default 0, model type for frustum. 0=depth camera, 1=3d lidar like VLP16 or similar
            always_send_full_costmap: True

local_costmap:
    local_costmap:
        ros__parameters:
            update_frequency: 7.0
            publish_frequency: 8.0
            global_frame: odom
            robot_base_frame: base_link
            use_sim_time: True
            rolling_window: true
            width: 100
            height: 100
            resolution: 0.2
            footprint: "[ [2.53, -0.859], [2.53, 0.859], [-0.393, 0.859], [-0.393, -0.859]]"
            plugins: ["stvl_layer", "inflation_layer"]
            inflation_layer:
                plugin: "nav2_costmap_2d::InflationLayer"
                cost_scaling_factor: 0.25
                inflation_radius: 10.5
            stvl_layer:
                plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
                enabled: true
                voxel_decay: 1.
                decay_model: 0
                voxel_size: 0.05
                track_unknown_space: true
                unknown_threshold: 15
                mark_threshold: 2
                footprint_clearing_enabled: true
                update_footprint_enabled: true
                combination_method: 1
                origin_z: 0.0
                publish_voxel_map: true
                transform_tolerance: 0.2
                mapping_mode: false
                map_save_duration: 60.0
                observation_sources: pointcloud_mark pointcloud_clear
                pointcloud_mark:
                    data_type: PointCloud2
                    topic: /lidar_points_filtered
                    marking: true
                    clearing: false
                    obstacle_range: 35.0          # meters
                    min_obstacle_height: 0.1     # default 0, meters
                    max_obstacle_height: 2.0     # default 3, meters
                    expected_update_rate: 0.0    # default 0, if not updating at this rate at least, remove from buffer
                    observation_persistence: 0.0 # default 0, use all measurements taken during now-value, 0=latest
                    inf_is_valid: false          # default false, for laser scans
                    filter: "passthrough"        # default passthrough, apply "voxel", "passthrough", or no filter to sensor data, recommend on     
                    voxel_min_points: 0          # default 0, minimum points per voxel for voxel filter
                    clear_after_reading: true    # default false, clear the buffer after the layer gets readings from it
                pointcloud_clear:
                    enabled: false                #default true, can be toggled on/off with associated service call
                    data_type: PointCloud2
                    topic: /lidar_points_filtered
                    marking: false
                    clearing: true
                    max_z: 15.0                  # default 0, meters
                    min_z: 0.5                  # default 10, meters
                    vertical_fov_angle: 0.523   # default 0.7, radians. For 3D lidars it's the symmetric FOV about the planar axis.
                    vertical_fov_padding: 0.05  # 3D Lidar only. Default 0, in meters 
                    horizontal_fov_angle: 6.29  # 3D lidar scanners like the VLP16 have 360 deg horizontal FOV.
                    decay_acceleration: 5.0     # default 0, 1/s^2. 
                    model_type: 1               # default 0, model type for frustum. 0=depth camera, 1=3d lidar like VLP16 or similar
            always_send_full_costmap: True

planner_server:
    ros__parameters:
        enable_stamped_cmd_vel: true
        planner_plugins: ["GridBased"]
        use_sim_time: True
        GridBased:
            plugin: "nav2_smac_planner::SmacPlannerHybrid" # In Iron and older versions, "/" was used instead of "::"
            downsample_costmap: False           # whether or not to downsample the map
            downsampling_factor: 2              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
            tolerance: 0.1                    # dist-to-goal heuristic cost (distance) for valid tolerance endpoints if exact goal cannot be found.
            allow_unknown: true                 # allow traveling in unknown space
            max_iterations: 9000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
            max_on_approach_iterations: 10000    # Maximum number of iterations after within tolerances to continue to try to find exact solution
            max_planning_time: 15.0              # max time in s for planner to plan, smooth
            motion_model_for_search: "REEDS_SHEPP"    # Hybrid-A* Dubin, Redds-Shepp
            angle_quantization_bins: 72         # Number of angle bins for search
            analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
            analytic_expansion_max_length: 4.5  # For Hybrid/Lattice nodes: The maximum length of the analytic expansion to be considered valid to prevent unsafe shortcutting
            analytic_expansion_max_cost: 200.0  # The maximum single cost for any part of an analytic expansion to contain and be valid, except when necessary on approach to goal
            analytic_expansion_max_cost_override: True  #  Whether or not to override the maximum cost setting if within critical distance to goal (ie probably required)
            minimum_turning_radius: 8.0        # minimum turning radius in m of path / vehicle
            reverse_penalty: 3.5               # Penalty to apply if motion is reversing, must be => 1
            change_penalty: 0.4                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
            non_straight_penalty: 1.3           # Penalty to apply if motion is non-straight, must be => 1
            cost_penalty: 4.0                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
            retrospective_penalty: 0.015
            lookup_table_size: 50.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
            cache_obstacle_heuristic: True     # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
            debug_visualizations: True         # For Hybrid nodes: Whether to publish expansions on the /expansions topic as an array of poses (the orientation has no meaning) and the path's footprints on the /planned_footprints topic. WARNING: heavy to compute and to display, for debug only as it degrades the performance.
            use_quadratic_cost_penalty: False
            downsample_obstacle_heuristic: False
            allow_primitive_interpolation: False
            smooth_path: True                  # If true, does a simple and quick smoothing post-processing to the path
            smoother:
                max_iterations: 500
                w_smooth: 0.3
                w_data: 0.5
                tolerance: 1.0e-10
                do_refinement: true
                refinement_num: 2

velocity_smoother:
    ros__parameters:
        enable_stamped_cmd_vel: true
        smoothing_frequency: 200.0
        scale_velocities: false
        feedback: "OPEN_LOOP"
        max_velocity: [3.0, 0.0, 1.6]
        min_velocity: [-3.0, 0.0, -1.6]
        deadband_velocity: [0.2, 0.0, 0.0]
        velocity_timeout: 1.0
        max_accel: [3.0, 0.0, 0.6]
        max_decel: [-3.0, 0.0, -3.2]
        odom_topic: "odom"
        odom_duration: 0.1
        use_realtime_priority: false

planner_server_rclcpp_node:
    ros__parameters:
        enable_stamped_cmd_vel: true
        use_sim_time: True

recoveries_server:
    ros__parameters:
        enable_stamped_cmd_vel: true
        costmap_topic: local_costmap/costmap_raw
        footprint_topic: local_costmap/published_footprint
        cycle_frequency: 10.0
        recovery_plugins: ["wait"]
        backup:
            plugin: "nav2_recoveries/BackUp"
        wait:
            plugin: "nav2_recoveries/Wait"
        global_frame: odom
        robot_base_frame: base_link
        transform_timeout: 0.1
        use_sim_time: true
        simulate_ahead_time: 2.0
        max_rotational_vel: 1.0
        min_rotational_vel: 0.4
        rotational_acc_lim: 3.2

docking_server:
  ros__parameters:
    enable_stamped_cmd_vel: true
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    dock_backwards: false
    dock_prestaging_tolerance: 0.5

    # Types of docks
    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false # true

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    # Dock instances
    # The following example illustrates configuring dock instances.
    # docks: ['home_dock']  # Input your docks here
    # home_dock:
    #   type: 'simple_charging_dock'
    #   frame: map
    #   pose: [0.0, 0.0, 0.0]

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
      use_collision_detection: true
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 5.0
      simulation_step: 0.1
      dock_collision_threshold: 0.3
collision_monitor:
    ros__parameters:
        use_sim_time: True
        enable_stamped_cmd_vel: true
        base_frame_id: "base_link"
        odom_frame_id: "odom"
        cmd_vel_in_topic: "cmd_vel_nav"
        cmd_vel_out_topic: "cmd_vel_collision"
        transform_tolerance: 0.76
        source_timeout: 5.0
        base_shift_correction: True
        stop_pub_timeout: 2.0
        # Polygons represent zone around the robot for "stop" and "slowdown" action types,
        # and robot footprint for "approach" action type.
        # Footprint could be "polygon" type with dynamically set footprint from footprint_topic
        # or "circle" type with static footprint set by radius. "footprint_topic" parameter
        # to be ignored in circular case.
        # [2.53, -0.859], [2.53, 0.859], [-0.393, 0.859], [-0.393, -0.859]
        polygons: ["Polygon700","Polygon500","PolygonStop","Polygon2000","FootprintApproach"]
        Polygon2000: # Named after 2000mm distance from footprint
            type: "polygon"
            points: "[[4.63, -2.369], [4.63, 2.369], [-1.903, 2.369], [-1.903, -2.369]]"
            action_type: "slowdown"
            min_points: 3
            visualize: True
            polygon_pub_topic: "polygon_slowdown2000"
            slowdown_ratio: 0.4 
        Polygon700: # Named after 700mm distance from footprint
            type: "polygon"
            points: "[[3.33, -1.569], [3.33, 1.569], [-1.103, 1.569], [-1.103, -1.569]]"
            action_type: "slowdown"
            min_points: 3
            visualize: True
            polygon_pub_topic: "polygon_slowdown500"
            slowdown_ratio: 0.3
        Polygon500: # Named after 500mm distance from footprint
            type: "polygon"
            points: "[[3.13, -1.369], [3.13, 1.369], [-0.903, 1.369], [-0.903, -1.369]]"
            action_type: "slowdown"
            min_points: 3
            visualize: True
            polygon_pub_topic: "polygon_slowdown300"
            slowdown_ratio: 0.1
        PolygonStop:
            type: "polygon"
            points: "[[3.63, -0.869], [3.63, 0.869], [-1.503, 0.869], [-1.503, -0.869]]"
            action_type: "stop"
            min_points: 2
            visualize: True
            polygon_pub_topic: "polygon_stop"
        FootprintApproach:
            type: "polygon"
            action_type: "approach"
            footprint_topic: "/local_costmap/published_footprint"
            time_before_collision: 1.5
            simulation_time_step: 0.1
            min_points: 5
            visualize: False
            enabled: True
        observation_sources: ["pointcloud2"]
        scan:
            type: "scan"
            topic: "/ouster/scan"
            enabled: True
        pointcloud2:
            type: "pointcloud"
            topic: "/lidar_points_filtered"
            min_height: 0.1
            max_height: 0.9
            enabled: True

```
