### ISSUE TITLE
Fix costmap obstacle layer

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#544]
## Bug report

**Required Info:**

- Operating System: Ubuntu 16.04
- Installation type: source
- Version or commit hash: `fa6144f67f3f5b5a0c6a2078982f73690b7a4147`
- DDS implementation: FAST-RTPS`
- Client library (if applicable):

#### Steps to reproduce issue
Launch nav stack in simulation using your [prefered method](https://github.com/ros-planning/navigation2/tree/master/nav2_bringup)

Enable ostacle layer on `nav2_params.yaml'

```
global_costmap:
  global_costmap:
    ros__parameters:
      obstacle_layer:
        enabled: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: False
        marking: True
```
Manually drop an object in gazebo, i.e. cardboard box.

#### Expected behavior

After enabling the visualization of the global costmap (or local costmap depending on which has the obstacle layer enabled), the costmap should refect the fact that an object was added to the environment.

#### Actual behavior

We don't see the obstacle :(
