### ISSUE TITLE
Dealing with dynamic obstacles that get 'stuck' in costmap

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#545]
## Bug report

**Required Info:**

- Operating System: Ubuntu 16.04
- Installation type: source
- Version or commit hash:
- DDS implementation: FAST-RTPS`
- Client library (if applicable):

#### Steps to reproduce issue
Launch nav stack in simulation using your [prefered method](https://github.com/ros-planning/navigation2/tree/master/nav2_bringup)

Make sure obstacle layer is ON in `nav2_params.yaml'

```
global_costmap:
  global_costmap:
    ros__parameters:
      obstacle_layer:
        enabled: True
      always_send_full_costmap: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
```

**Make sure clearing and marking are `True`**

Manually drop an object in gazebo, i.e. cardboard box, then manually remove the object.

#### Expected behavior

When the object is added, the obstacle layer in costmap should increase the cost of cells where the dynamic object was placed, likewise it should completely remove the cost once the object is removed.

#### Actual behavior

The cost is not completely clear once the object is removed. See video below.
