### ISSUE TITLE
dwb_controller without the static layer causes a partial costmap

### ISSUE THREAD

**Issue by rotu** [ros-planning/navigation2#903]
dwb_controller relies on the static_layer plugin to set the map bounds. So when I exclude this plugin, the local costmap comes out truncated (RViz screenshot). Also, dwb_controller spews out warnings. This problem goes away when adding the `nav2_costmap_2d::StaticLayer` plugin, even with `static_layer.enabled: False`.

RViz screenshot. Notice the abrupt cutoff on the top-left and the missing costmap recognition around the laser hits on the right side:
![Screenshot from 2019-07-01 13-59-05](https://user-images.githubusercontent.com/119948/60460084-6afabf00-9c08-11e9-86e1-1f232476bbd8.png)

Local costmap settings:
```
local_costmap:
  dwb_controller:
    ros__parameters:
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      global_frame: map
      always_send_full_costmap: true
      use_sim_time: false
      robot_radius: 0.17
      inflation_layer:
        cost_scaling_factor: 3.0
      obstacle_layer:
        enabled: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True
```

Logging warnings:
```[dwb_controller-4] [WARN] [local_costmap.dwb_controller]: Sensor origin at (-0.05, 2.29) is out of map bounds. The costmap cannot raytrace for it.
[dwb_controller-4] [WARN] [local_costmap.dwb_controller]: Sensor origin at (-0.05, 2.29) is out of map bounds. The costmap cannot raytrace for it.
[dwb_controller-4] [WARN] [local_costmap.dwb_controller]: Sensor origin at (-0.05, 2.29) is out of map bounds. The costmap cannot raytrace for it.
[dwb_controller-4] [WARN] [local_costmap.dwb_controller]: Sensor origin at (-0.05, 2.29) is out of map bounds. The costmap cannot raytrace for it.
[dwb_controller-4] [WARN] [local_costmap.dwb_controller]: Sensor origin at (-0.05, 2.29) is out of map bounds. The costmap cannot raytrace for it.
[dwb_controller-4] [WARN] [local_costmap.dwb_controller]: Sensor origin at (-0.05, 2.29) is out of map bounds. The costmap cannot raytrace for it.
```
