### ISSUE TITLE
[Map Server] No response on running map_server

### ISSUE THREAD

**Issue by shikharvaish28** [ros-planning/navigation2#975]
I have built and sourced the ```navigation2```. After sourcing using ```source build/navigation2_ws/install/setup.bash```, I run 
```bash
./build/navigation2_ws/build/nav2_map_server/map_server /home/hipert/Downloads/random/navigation2/map.yaml
```
and the terminal gets stuck on this 
```bash
[INFO] [map_server]: Creating
```

The content of my ```map.yaml``` file is 
```yaml
image: map.pgm
resolution: 0.05
origin: [-9.38389, -11.5719, 0.0000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196
```

I have tried with the ```map.pgm``` as well but nothing seems to work.
 Also, on running the ```rviz``` I cannot see the topic of map add.

Note: On running ```source navigation2/install/setup.bash```, it says that directory not found.

 Can anyone help me with it? What is the expected nature of the map server?
